"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BGM_DATA_MAP = exports.SE_POINTER_TABLE = exports.AudioService = exports.SpriteAnimationService = exports.SpriteService = exports.SkillService = exports.MatchSceneService = exports.MatchConfigService = exports.MatchHudService = exports.MatchAuxService = exports.MatchTurnService = exports.MatchEngineService = exports.TeamRosterService = exports.PlayerQueryService = exports.decodeChar = exports.CharMap = exports.getScriptData = exports.ScriptLoader = exports.initScriptOpcodes = exports.WAIT_FRAME_TABLE = exports.ScriptOpcodes = exports.ScriptEngine = exports.ResultSceneController = exports.PASSWORD_DISPATCH_TABLE = exports.NMI_CALLBACK_TABLE = exports.BootBackgroundRenderer = exports.PasswordCallbackHandler = exports.TitleSceneController = exports.InterruptService = exports.HardwareInitService = exports.NmiCallbackIndex = exports.BootRouter = exports.GameSystemService = void 0;
/**
 * prg/code/index.ts — 业务逻辑层 (Service) 聚合出口
 * 按业务域分包: system / scene / story / player / team / match / skill / sprite / audio
 */
var GameSystemService_1 = require("./system/GameSystemService");
Object.defineProperty(exports, "GameSystemService", { enumerable: true, get: function () { return GameSystemService_1.GameSystemService; } });
var BootRouter_1 = require("./system/BootRouter");
Object.defineProperty(exports, "BootRouter", { enumerable: true, get: function () { return BootRouter_1.BootRouter; } });
Object.defineProperty(exports, "NmiCallbackIndex", { enumerable: true, get: function () { return BootRouter_1.NmiCallbackIndex; } });
var HardwareInitService_1 = require("./system/HardwareInitService");
Object.defineProperty(exports, "HardwareInitService", { enumerable: true, get: function () { return HardwareInitService_1.HardwareInitService; } });
var InterruptService_1 = require("./system/InterruptService");
Object.defineProperty(exports, "InterruptService", { enumerable: true, get: function () { return InterruptService_1.InterruptService; } });
var TitleSceneController_1 = require("./scene/TitleSceneController");
Object.defineProperty(exports, "TitleSceneController", { enumerable: true, get: function () { return TitleSceneController_1.TitleSceneController; } });
var PasswordCallbackHandler_1 = require("./scene/PasswordCallbackHandler");
Object.defineProperty(exports, "PasswordCallbackHandler", { enumerable: true, get: function () { return PasswordCallbackHandler_1.PasswordCallbackHandler; } });
var BootBackgroundRenderer_1 = require("./scene/BootBackgroundRenderer");
Object.defineProperty(exports, "BootBackgroundRenderer", { enumerable: true, get: function () { return BootBackgroundRenderer_1.BootBackgroundRenderer; } });
var bank02_tables_1 = require("../data/tables/bank02-tables");
Object.defineProperty(exports, "NMI_CALLBACK_TABLE", { enumerable: true, get: function () { return bank02_tables_1.NMI_CALLBACK_TABLE; } });
Object.defineProperty(exports, "PASSWORD_DISPATCH_TABLE", { enumerable: true, get: function () { return bank02_tables_1.PASSWORD_DISPATCH_TABLE; } });
var ResultSceneController_1 = require("./scene/ResultSceneController");
Object.defineProperty(exports, "ResultSceneController", { enumerable: true, get: function () { return ResultSceneController_1.ResultSceneController; } });
var ScriptEngine_1 = require("./story/ScriptEngine");
Object.defineProperty(exports, "ScriptEngine", { enumerable: true, get: function () { return ScriptEngine_1.ScriptEngine; } });
var ScriptOpcodes_1 = require("./story/ScriptOpcodes");
Object.defineProperty(exports, "ScriptOpcodes", { enumerable: true, get: function () { return ScriptOpcodes_1.ScriptOpcodes; } });
Object.defineProperty(exports, "WAIT_FRAME_TABLE", { enumerable: true, get: function () { return ScriptOpcodes_1.WAIT_FRAME_TABLE; } });
Object.defineProperty(exports, "initScriptOpcodes", { enumerable: true, get: function () { return ScriptOpcodes_1.initScriptOpcodes; } });
var ScriptLoader_1 = require("./story/ScriptLoader");
Object.defineProperty(exports, "ScriptLoader", { enumerable: true, get: function () { return ScriptLoader_1.ScriptLoader; } });
Object.defineProperty(exports, "getScriptData", { enumerable: true, get: function () { return ScriptLoader_1.getScriptData; } });
var CharMap_1 = require("./story/CharMap");
Object.defineProperty(exports, "CharMap", { enumerable: true, get: function () { return CharMap_1.CharMap; } });
Object.defineProperty(exports, "decodeChar", { enumerable: true, get: function () { return CharMap_1.decodeChar; } });
var PlayerQueryService_1 = require("./player/PlayerQueryService");
Object.defineProperty(exports, "PlayerQueryService", { enumerable: true, get: function () { return PlayerQueryService_1.PlayerQueryService; } });
var TeamRosterService_1 = require("./team/TeamRosterService");
Object.defineProperty(exports, "TeamRosterService", { enumerable: true, get: function () { return TeamRosterService_1.TeamRosterService; } });
var MatchEngineService_1 = require("./match/MatchEngineService");
Object.defineProperty(exports, "MatchEngineService", { enumerable: true, get: function () { return MatchEngineService_1.MatchEngineService; } });
var MatchTurnService_1 = require("./match/MatchTurnService");
Object.defineProperty(exports, "MatchTurnService", { enumerable: true, get: function () { return MatchTurnService_1.MatchTurnService; } });
var MatchAuxService_1 = require("./match/MatchAuxService");
Object.defineProperty(exports, "MatchAuxService", { enumerable: true, get: function () { return MatchAuxService_1.MatchAuxService; } });
var MatchHudService_1 = require("./match/MatchHudService");
Object.defineProperty(exports, "MatchHudService", { enumerable: true, get: function () { return MatchHudService_1.MatchHudService; } });
var MatchConfigService_1 = require("./match/MatchConfigService");
Object.defineProperty(exports, "MatchConfigService", { enumerable: true, get: function () { return MatchConfigService_1.MatchConfigService; } });
var MatchSceneService_1 = require("./match/MatchSceneService");
Object.defineProperty(exports, "MatchSceneService", { enumerable: true, get: function () { return MatchSceneService_1.MatchSceneService; } });
var SkillService_1 = require("./skill/SkillService");
Object.defineProperty(exports, "SkillService", { enumerable: true, get: function () { return SkillService_1.SkillService; } });
var SpriteService_1 = require("./sprite/SpriteService");
Object.defineProperty(exports, "SpriteService", { enumerable: true, get: function () { return SpriteService_1.SpriteService; } });
var SpriteAnimationService_1 = require("./sprite/SpriteAnimationService");
Object.defineProperty(exports, "SpriteAnimationService", { enumerable: true, get: function () { return SpriteAnimationService_1.SpriteAnimationService; } });
var AudioService_1 = require("./audio/AudioService");
Object.defineProperty(exports, "AudioService", { enumerable: true, get: function () { return AudioService_1.AudioService; } });
Object.defineProperty(exports, "SE_POINTER_TABLE", { enumerable: true, get: function () { return AudioService_1.SE_POINTER_TABLE; } });
Object.defineProperty(exports, "BGM_DATA_MAP", { enumerable: true, get: function () { return AudioService_1.BGM_DATA_MAP; } });
