/**
 * Verify bank_00 generated bytes match ROM
 */
import fs from 'fs';

const ROM_PATH = 'rom.nes';
// Read ROM
const rom = fs.readFileSync(ROM_PATH);
const prgCount = rom[4];
const prgStart = 16;
const bankSize = 8192;

console.log('ROM PRG banks:', prgCount, 'bank size:', bankSize);

// Extract ROM bank 0
const romBank0 = Array.from(rom.slice(prgStart, prgStart + bankSize));
console.log('ROM bank 0 size:', romBank0.length);

// Now try to load the TS module and generate bytes
// Since we can't easily import TS, let's run a test via node with --loader
// Instead, let's check if there's a way to generate via an existing script

// For now, let's check the structure of the file
const filePath = 'src/tsnes/tsubasa-hex2asm/prg_banks/prg_bank_00_dispatch_scene_engine.ts';
const content = fs.readFileSync(filePath, 'utf8');

// Find all functions
const funcs = [];
const funcRe = /^function (build\w+)\(\): readonly number\[\] \{[\s\S]*?\n\}/gm;
let m;
while ((m = funcRe.exec(content)) !== null) {
  funcs.push({ name: m[1], full: m[0], start: m.index, end: m.index + m[0].length });
}

console.log('\nFunctions found:', funcs.length);
funcs.forEach(f => console.log(`  ${f.name}: ${f.end - f.start} chars, line ${content.slice(0, f.start).split('\n').length}`));

// Check which functions use asm vs arrays
for (const f of funcs) {
  const usesAsm = f.full.includes('return asm`');
  const usesArray = f.full.includes('return [');
  console.log(`  ${f.name}: asm=${usesAsm} arr=${usesArray}`);
}
