"""
V0.17.1 — 从 nbm-png-manifest.json 生成 miniprogram/utils/sudoku/nbmAssets.ts.

索引所有 miniprogram/assets/nbm/*.nbm.png, 按功能分组 + 常量 URL.
"""
import os
import json
import re

WORKSPACE = r'D:\studio\github\monkeycode\src\nds\EssentialSudokuDS'
MANIFEST = os.path.join(WORKSPACE, 'rom-data', 'extracted', 'nbm-png-manifest.json')
OUT_PATH = os.path.join(WORKSPACE, 'miniprogram', 'utils', 'sudoku', 'nbmAssets.ts')

ROOT_PREFIX = '/assets/nbm/'


def sanitize(name: str) -> str:
    # strip trailing '.nbm' so constants read like NBM_NUMCLO_WAKU
    base = re.sub(r'\.nbm$', '', name)
    s = re.sub(r'[^a-zA-Z0-9_]', '_', base)
    if re.match(r'^[0-9]', s):
        s = '_' + s
    return s


def main():
    with open(MANIFEST, 'r', encoding='utf-8') as f:
        manifest = json.load(f)

    lines: list[str] = []
    lines.append('// AUTO-GENERATED by scripts/gen_nbm_assets_ts.py — DO NOT EDIT')
    lines.append('// NBM decoded resources → miniprogram/assets/nbm PNG URLs')
    lines.append('')

    # individual constants
    entries = manifest.get('entries', [])
    const_by_name: dict[str, str] = {}
    for e in entries:
        const = sanitize(e['name']).upper()
        const_by_name[e['name']] = const
        url = ROOT_PREFIX + e['png']
        lines.append(f"export const NBM_{const} = '{url}';")

    lines.append('')
    lines.append('/** Full flat list of all 42 NBM assets. */')
    lines.append('export const NBM_ALL = [')
    for e in entries:
        const = const_by_name[e['name']]
        lines.append(f'  NBM_{const},')
    lines.append('];')

    # functional groups — 按玩法模式区分 (numclo/pazl = picture puzzle, 数独界面禁用)
    groups: dict[str, list[str]] = {}
    for e in entries:
        name = e['name']
        const = const_by_name[name]
        if 'numclo' in name or 'pazl' in name:
            groups.setdefault('PICTURE_PUZZLE', []).append(f'NBM_{const}')
        elif 'select' in name:
            groups.setdefault('MENU_SELECT', []).append(f'NBM_{const}')
        elif 'wireless' in name:
            groups.setdefault('WIRELESS', []).append(f'NBM_{const}')
        elif 'staff' in name:
            groups.setdefault('STAFF', []).append(f'NBM_{const}')
        elif name in ('title.nbm', 'title2.nbm'):
            groups.setdefault('TITLE', []).append(f'NBM_{const}')
        elif name in ('download.nbm', 'dwlogo.nbm', 'license.nbm', 'tutorial_00.nbm', 'usa.nbm', 'setu03.nbm', 'menu_csol.nbm'):
            groups.setdefault('MISC', []).append(f'NBM_{const}')
        else:
            groups.setdefault('OTHER', []).append(f'NBM_{const}')

    lines.append('')
    lines.append('/**')
    lines.append(' * 模式资源归属（重要）:')
    lines.append(' *  - Essential Sudoku DS = 数独 number puzzle, 题目数据来自 numple0-9.data.')
    lines.append(' *  - numclo 系 / pazl 系 NBM 是图画谜题 picture puzzle 模式的资源（另一种玩法,')
    lines.append(' *    1:1 还原目标下必须接入, 不是弃用资源; V0.15.2 "wrong format" 标注已修正）.')
    lines.append(' *  - 数独界面禁止引用 PICTURE_PUZZLE 组资源; 该组资源专供 picture puzzle 玩法界面.')
    lines.append(' */')
    lines.append('')
    lines.append('/** 数独模式通用 UI 资源 (菜单/设置/教程/下载/许可/地区). */')
    for gname in ('MISC', 'PICTURE_PUZZLE', 'MENU_SELECT', 'STAFF', 'TITLE', 'WIRELESS', 'OTHER'):
        consts = groups.get(gname)
        if not consts:
            continue
        if gname == 'PICTURE_PUZZLE':
            lines.append('/** 图画谜题 (picture puzzle) 模式资源 — 数独界面禁用. */')
        elif gname == 'MENU_SELECT':
            lines.append('/** 数独模式选择界面按钮 (select1/3/4/6). */')
        lines.append(f"export const NBM_GROUP_{gname} = [")
        for c in consts:
            lines.append(f'  {c},')
        lines.append('];')
        lines.append('')

    # helpers
    lines.append('')
    lines.append('/** Resolve an NBM asset URL by its decoded name (without .nbm.bmp/.nbm.png extension). */')
    lines.append('export function nbmUrl(name: string): string | undefined {')
    lines.append('  const constName = `NBM_${name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/\\.nbm$/i, "").toUpperCase()}`;')
    lines.append('  const map: Record<string, string> = {')
    for e in entries:
        const = const_by_name[e['name']]
        lines.append(f"    '{const}': NBM_{const},")
    lines.append('  };')
    lines.append('  return map[constName];')
    lines.append('}')
    lines.append('')

    # summary metadata
    lines.append('/** Summary (total PNG bytes ≈ {0} KB). */'.format(manifest.get('totalKb', '??')))
    lines.append(f"export const NBM_MANIFEST = {{ total: {len(entries)}, totalBytes: {manifest.get('totalBytes', 0)} }};")
    lines.append('')

    with open(OUT_PATH, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f'Wrote {OUT_PATH} ({len(entries)} entries)')


if __name__ == '__main__':
    main()
