// AUTO-GENERATED by scripts/gen_nbm_assets_ts.py — DO NOT EDIT
// NBM decoded resources → miniprogram/assets/nbm PNG URLs

export const NBM_DOWNLOAD = '/assets/nbm/download.nbm.png';
export const NBM_DWLOGO = '/assets/nbm/dwlogo.nbm.png';
export const NBM_LICENSE = '/assets/nbm/license.nbm.png';
export const NBM_MENU_CSOL = '/assets/nbm/menu_csol.nbm.png';
export const NBM_NUMCLO_00 = '/assets/nbm/numclo_00.nbm.png';
export const NBM_NUMCLO_WAKU = '/assets/nbm/numclo_waku.nbm.png';
export const NBM_PAZL_SELECT = '/assets/nbm/pazl_select.nbm.png';
export const NBM_PAZL_SELECT2A = '/assets/nbm/pazl_select2a.nbm.png';
export const NBM_PAZL_SELECT2B = '/assets/nbm/pazl_select2b.nbm.png';
export const NBM_PAZL_SELECT2C = '/assets/nbm/pazl_select2c.nbm.png';
export const NBM_PAZL_YAJIRUSI = '/assets/nbm/pazl_yajirusi.nbm.png';
export const NBM_SELECT1 = '/assets/nbm/select1.nbm.png';
export const NBM_SELECT3 = '/assets/nbm/select3.nbm.png';
export const NBM_SELECT4 = '/assets/nbm/select4.nbm.png';
export const NBM_SELECT6 = '/assets/nbm/select6.nbm.png';
export const NBM_SETU03 = '/assets/nbm/setu03.nbm.png';
export const NBM_STAFF00 = '/assets/nbm/staff00.nbm.png';
export const NBM_STAFF01 = '/assets/nbm/staff01.nbm.png';
export const NBM_STAFF02 = '/assets/nbm/staff02.nbm.png';
export const NBM_STAFF03 = '/assets/nbm/staff03.nbm.png';
export const NBM_STAFF04 = '/assets/nbm/staff04.nbm.png';
export const NBM_STAFF05 = '/assets/nbm/staff05.nbm.png';
export const NBM_STAFF06 = '/assets/nbm/staff06.nbm.png';
export const NBM_STAFF07 = '/assets/nbm/staff07.nbm.png';
export const NBM_STAFF08 = '/assets/nbm/staff08.nbm.png';
export const NBM_STAFF09 = '/assets/nbm/staff09.nbm.png';
export const NBM_STAFF10 = '/assets/nbm/staff10.nbm.png';
export const NBM_STAFF11 = '/assets/nbm/staff11.nbm.png';
export const NBM_STAFF12 = '/assets/nbm/staff12.nbm.png';
export const NBM_TITLE = '/assets/nbm/title.nbm.png';
export const NBM_TITLE2 = '/assets/nbm/title2.nbm.png';
export const NBM_TUTORIAL_00 = '/assets/nbm/tutorial_00.nbm.png';
export const NBM_USA = '/assets/nbm/usa.nbm.png';
export const NBM_WIRELESS_ON = '/assets/nbm/wireless_on.nbm.png';
export const NBM_WIRELESS_STRENGTH_LEVEL_0_B = '/assets/nbm/wireless_strength_level_0_b.nbm.png';
export const NBM_WIRELESS_STRENGTH_LEVEL_0_W = '/assets/nbm/wireless_strength_level_0_w.nbm.png';
export const NBM_WIRELESS_STRENGTH_LEVEL_1_B = '/assets/nbm/wireless_strength_level_1_b.nbm.png';
export const NBM_WIRELESS_STRENGTH_LEVEL_1_W = '/assets/nbm/wireless_strength_level_1_w.nbm.png';
export const NBM_WIRELESS_STRENGTH_LEVEL_2_B = '/assets/nbm/wireless_strength_level_2_b.nbm.png';
export const NBM_WIRELESS_STRENGTH_LEVEL_2_W = '/assets/nbm/wireless_strength_level_2_w.nbm.png';
export const NBM_WIRELESS_STRENGTH_LEVEL_3_B = '/assets/nbm/wireless_strength_level_3_b.nbm.png';
export const NBM_WIRELESS_STRENGTH_LEVEL_3_W = '/assets/nbm/wireless_strength_level_3_w.nbm.png';

/** Full flat list of all 42 NBM assets. */
export const NBM_ALL = [
  NBM_DOWNLOAD,
  NBM_DWLOGO,
  NBM_LICENSE,
  NBM_MENU_CSOL,
  NBM_NUMCLO_00,
  NBM_NUMCLO_WAKU,
  NBM_PAZL_SELECT,
  NBM_PAZL_SELECT2A,
  NBM_PAZL_SELECT2B,
  NBM_PAZL_SELECT2C,
  NBM_PAZL_YAJIRUSI,
  NBM_SELECT1,
  NBM_SELECT3,
  NBM_SELECT4,
  NBM_SELECT6,
  NBM_SETU03,
  NBM_STAFF00,
  NBM_STAFF01,
  NBM_STAFF02,
  NBM_STAFF03,
  NBM_STAFF04,
  NBM_STAFF05,
  NBM_STAFF06,
  NBM_STAFF07,
  NBM_STAFF08,
  NBM_STAFF09,
  NBM_STAFF10,
  NBM_STAFF11,
  NBM_STAFF12,
  NBM_TITLE,
  NBM_TITLE2,
  NBM_TUTORIAL_00,
  NBM_USA,
  NBM_WIRELESS_ON,
  NBM_WIRELESS_STRENGTH_LEVEL_0_B,
  NBM_WIRELESS_STRENGTH_LEVEL_0_W,
  NBM_WIRELESS_STRENGTH_LEVEL_1_B,
  NBM_WIRELESS_STRENGTH_LEVEL_1_W,
  NBM_WIRELESS_STRENGTH_LEVEL_2_B,
  NBM_WIRELESS_STRENGTH_LEVEL_2_W,
  NBM_WIRELESS_STRENGTH_LEVEL_3_B,
  NBM_WIRELESS_STRENGTH_LEVEL_3_W,
];

/** select3.nbm 切片: 选项页按钮标签普通态. */
export const NBM_SELECT3_CLEAR_NORMAL = '/assets/nbm/select3_clear_normal.png';
export const NBM_SELECT3_RATE_NORMAL = '/assets/nbm/select3_rate_normal.png';
export const NBM_SELECT3_SE_VOLUME_NORMAL = '/assets/nbm/select3_se_volume_normal.png';
export const NBM_SELECT3_CREDITS_NORMAL = '/assets/nbm/select3_credits_normal.png';
export const NBM_SELECT3_BGM_VOLUME_NORMAL = '/assets/nbm/select3_bgm_volume_normal.png';

/** select1.nbm 切片: 数独数字键盘/动作按钮/Difficulty A-E/上下箭头. */
export const NBM_SELECT1_N_0_NORMAL = '/assets/nbm/select1_n_0_normal.png';
export const NBM_SELECT1_N_1_NORMAL = '/assets/nbm/select1_n_1_normal.png';
export const NBM_SELECT1_N_2_NORMAL = '/assets/nbm/select1_n_2_normal.png';
export const NBM_SELECT1_N_3_NORMAL = '/assets/nbm/select1_n_3_normal.png';
export const NBM_SELECT1_N_4_NORMAL = '/assets/nbm/select1_n_4_normal.png';
export const NBM_SELECT1_N_5_NORMAL = '/assets/nbm/select1_n_5_normal.png';
export const NBM_SELECT1_N_6_NORMAL = '/assets/nbm/select1_n_6_normal.png';
export const NBM_SELECT1_N_7_NORMAL = '/assets/nbm/select1_n_7_normal.png';
export const NBM_SELECT1_N_8_NORMAL = '/assets/nbm/select1_n_8_normal.png';
export const NBM_SELECT1_N_9_NORMAL = '/assets/nbm/select1_n_9_normal.png';
export const NBM_SELECT1_N_0_SELECTED = '/assets/nbm/select1_n_0_selected.png';
export const NBM_SELECT1_N_1_SELECTED = '/assets/nbm/select1_n_1_selected.png';
export const NBM_SELECT1_N_2_SELECTED = '/assets/nbm/select1_n_2_selected.png';
export const NBM_SELECT1_N_3_SELECTED = '/assets/nbm/select1_n_3_selected.png';
export const NBM_SELECT1_N_4_SELECTED = '/assets/nbm/select1_n_4_selected.png';
export const NBM_SELECT1_N_5_SELECTED = '/assets/nbm/select1_n_5_selected.png';
export const NBM_SELECT1_N_6_SELECTED = '/assets/nbm/select1_n_6_selected.png';
export const NBM_SELECT1_N_7_SELECTED = '/assets/nbm/select1_n_7_selected.png';
export const NBM_SELECT1_N_8_SELECTED = '/assets/nbm/select1_n_8_selected.png';
export const NBM_SELECT1_N_9_SELECTED = '/assets/nbm/select1_n_9_selected.png';
export const NBM_SELECT1_START_NORMAL = '/assets/nbm/select1_start_normal.png';
export const NBM_SELECT1_CLEARED_NORMAL = '/assets/nbm/select1_cleared_normal.png';
export const NBM_SELECT1_RETURN_NORMAL = '/assets/nbm/select1_return_normal.png';
export const NBM_SELECT1_START_SELECTED = '/assets/nbm/select1_start_selected.png';
export const NBM_SELECT1_CLEARED_SELECTED = '/assets/nbm/select1_cleared_selected.png';
export const NBM_SELECT1_RETURN_SELECTED = '/assets/nbm/select1_return_selected.png';
export const NBM_SELECT1_DIFF_A_NORMAL = '/assets/nbm/select1_diff_a_normal.png';
export const NBM_SELECT1_DIFF_B_NORMAL = '/assets/nbm/select1_diff_b_normal.png';
export const NBM_SELECT1_DIFF_C_NORMAL = '/assets/nbm/select1_diff_c_normal.png';
export const NBM_SELECT1_DIFF_D_NORMAL = '/assets/nbm/select1_diff_d_normal.png';
export const NBM_SELECT1_DIFF_E_NORMAL = '/assets/nbm/select1_diff_e_normal.png';
export const NBM_SELECT1_UP_NORMAL = '/assets/nbm/select1_up_normal.png';
export const NBM_SELECT1_UP_SELECTED = '/assets/nbm/select1_up_selected.png';
export const NBM_SELECT1_DOWN_NORMAL = '/assets/nbm/select1_down_normal.png';
export const NBM_SELECT1_DOWN_SELECTED = '/assets/nbm/select1_down_selected.png';

/** select4.nbm 切片: 主菜单模式按钮 (Number/Picture × 2 帧动画). */
export const NBM_SELECT4_NUMBER_A = '/assets/nbm/select4_number_a.png';
export const NBM_SELECT4_PICTURE_A = '/assets/nbm/select4_picture_a.png';
export const NBM_SELECT4_NUMBER_B = '/assets/nbm/select4_number_b.png';
export const NBM_SELECT4_PICTURE_B = '/assets/nbm/select4_picture_b.png';

/** numclo_00.nbm 切片: 图画谜题调色板按钮 (5 色 + 擦除). */
export const NBM_NUMCLO00_COLOR_1_RED = '/assets/nbm/numclo00_color_1_red.png';
export const NBM_NUMCLO00_COLOR_2_YELLOW = '/assets/nbm/numclo00_color_2_yellow.png';
export const NBM_NUMCLO00_COLOR_3_BLUE = '/assets/nbm/numclo00_color_3_blue.png';
export const NBM_NUMCLO00_COLOR_4_GREEN = '/assets/nbm/numclo00_color_4_green.png';
export const NBM_NUMCLO00_ERASE = '/assets/nbm/numclo00_erase.png';
export const NBM_NUMCLO00_CLEAR = '/assets/nbm/numclo00_clear.png';

/** pazl_select2b.nbm 切片: 图画谜题菜单 Return 按钮 (普通/选中态). */
export const NBM_PAZL_SELECT2B_RETURN_NORMAL = '/assets/nbm/pazl_select2b_return_normal.png';
export const NBM_PAZL_SELECT2B_RETURN_SELECTED = '/assets/nbm/pazl_select2b_return_selected.png';

/**
 * 模式资源归属（重要）:
 *  - Essential Sudoku DS = 数独 number puzzle, 题目数据来自 numple0-9.data.
 *  - numclo 系 / pazl 系 NBM 是图画谜题 picture puzzle 模式的资源（另一种玩法,
 *    1:1 还原目标下必须接入, 不是弃用资源; V0.15.2 "wrong format" 标注已修正）.
 *  - 数独界面禁止引用 PICTURE_PUZZLE 组资源; 该组资源专供 picture puzzle 玩法界面.
 */

/** 数独模式通用 UI 资源 (菜单/设置/教程/下载/许可/地区). */
export const NBM_GROUP_MISC = [
  NBM_DOWNLOAD,
  NBM_DWLOGO,
  NBM_LICENSE,
  NBM_MENU_CSOL,
  NBM_SETU03,
  NBM_TUTORIAL_00,
  NBM_USA,
];

/** 图画谜题 (picture puzzle) 模式资源 — 数独界面禁用. */
export const NBM_GROUP_PICTURE_PUZZLE = [
  NBM_NUMCLO_00,
  NBM_NUMCLO_WAKU,
  NBM_PAZL_SELECT,
  NBM_PAZL_SELECT2A,
  NBM_PAZL_SELECT2B,
  NBM_PAZL_SELECT2C,
  NBM_PAZL_YAJIRUSI,
  NBM_NUMCLO00_COLOR_1_RED,
  NBM_NUMCLO00_COLOR_2_YELLOW,
  NBM_NUMCLO00_COLOR_3_BLUE,
  NBM_NUMCLO00_COLOR_4_GREEN,
  NBM_NUMCLO00_ERASE,
  NBM_NUMCLO00_CLEAR,
  NBM_PAZL_SELECT2B_RETURN_NORMAL,
  NBM_PAZL_SELECT2B_RETURN_SELECTED,
];

/** 数独模式选择界面按钮 (select1/3/4/6). */
export const NBM_GROUP_MENU_SELECT = [
  NBM_SELECT1,
  NBM_SELECT3,
  NBM_SELECT4,
  NBM_SELECT6,
  NBM_SELECT1_N_0_NORMAL,
  NBM_SELECT1_N_1_NORMAL,
  NBM_SELECT1_N_2_NORMAL,
  NBM_SELECT1_N_3_NORMAL,
  NBM_SELECT1_N_4_NORMAL,
  NBM_SELECT1_N_5_NORMAL,
  NBM_SELECT1_N_6_NORMAL,
  NBM_SELECT1_N_7_NORMAL,
  NBM_SELECT1_N_8_NORMAL,
  NBM_SELECT1_N_9_NORMAL,
  NBM_SELECT1_N_0_SELECTED,
  NBM_SELECT1_N_1_SELECTED,
  NBM_SELECT1_N_2_SELECTED,
  NBM_SELECT1_N_3_SELECTED,
  NBM_SELECT1_N_4_SELECTED,
  NBM_SELECT1_N_5_SELECTED,
  NBM_SELECT1_N_6_SELECTED,
  NBM_SELECT1_N_7_SELECTED,
  NBM_SELECT1_N_8_SELECTED,
  NBM_SELECT1_N_9_SELECTED,
  NBM_SELECT1_START_NORMAL,
  NBM_SELECT1_CLEARED_NORMAL,
  NBM_SELECT1_RETURN_NORMAL,
  NBM_SELECT1_START_SELECTED,
  NBM_SELECT1_CLEARED_SELECTED,
  NBM_SELECT1_RETURN_SELECTED,
  NBM_SELECT1_DIFF_A_NORMAL,
  NBM_SELECT1_DIFF_B_NORMAL,
  NBM_SELECT1_DIFF_C_NORMAL,
  NBM_SELECT1_DIFF_D_NORMAL,
  NBM_SELECT1_DIFF_E_NORMAL,
  NBM_SELECT1_UP_NORMAL,
  NBM_SELECT1_UP_SELECTED,
  NBM_SELECT1_DOWN_NORMAL,
  NBM_SELECT1_DOWN_SELECTED,
  NBM_SELECT4_NUMBER_A,
  NBM_SELECT4_PICTURE_A,
  NBM_SELECT4_NUMBER_B,
  NBM_SELECT4_PICTURE_B,
];

export const NBM_GROUP_OPTIONS_SLICE = [
  NBM_SELECT3_CLEAR_NORMAL,
  NBM_SELECT3_RATE_NORMAL,
  NBM_SELECT3_SE_VOLUME_NORMAL,
  NBM_SELECT3_CREDITS_NORMAL,
  NBM_SELECT3_BGM_VOLUME_NORMAL,
];

export const NBM_GROUP_STAFF = [
  NBM_STAFF00,
  NBM_STAFF01,
  NBM_STAFF02,
  NBM_STAFF03,
  NBM_STAFF04,
  NBM_STAFF05,
  NBM_STAFF06,
  NBM_STAFF07,
  NBM_STAFF08,
  NBM_STAFF09,
  NBM_STAFF10,
  NBM_STAFF11,
  NBM_STAFF12,
];

export const NBM_GROUP_TITLE = [
  NBM_TITLE,
  NBM_TITLE2,
];

export const NBM_GROUP_WIRELESS = [
  NBM_WIRELESS_ON,
  NBM_WIRELESS_STRENGTH_LEVEL_0_B,
  NBM_WIRELESS_STRENGTH_LEVEL_0_W,
  NBM_WIRELESS_STRENGTH_LEVEL_1_B,
  NBM_WIRELESS_STRENGTH_LEVEL_1_W,
  NBM_WIRELESS_STRENGTH_LEVEL_2_B,
  NBM_WIRELESS_STRENGTH_LEVEL_2_W,
  NBM_WIRELESS_STRENGTH_LEVEL_3_B,
  NBM_WIRELESS_STRENGTH_LEVEL_3_W,
];


/** Resolve an NBM asset URL by its decoded name (without .nbm.bmp/.nbm.png extension). */
export function nbmUrl(name: string): string | undefined {
  const constName = `NBM_${name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/\.nbm$/i, "").toUpperCase()}`;
  const map: Record<string, string> = {
    'DOWNLOAD': NBM_DOWNLOAD,
    'DWLOGO': NBM_DWLOGO,
    'LICENSE': NBM_LICENSE,
    'MENU_CSOL': NBM_MENU_CSOL,
    'NUMCLO_00': NBM_NUMCLO_00,
    'NUMCLO_WAKU': NBM_NUMCLO_WAKU,
    'PAZL_SELECT': NBM_PAZL_SELECT,
    'PAZL_SELECT2A': NBM_PAZL_SELECT2A,
    'PAZL_SELECT2B': NBM_PAZL_SELECT2B,
    'PAZL_SELECT2C': NBM_PAZL_SELECT2C,
    'PAZL_YAJIRUSI': NBM_PAZL_YAJIRUSI,
    'SELECT1': NBM_SELECT1,
    'SELECT3': NBM_SELECT3,
    'SELECT4': NBM_SELECT4,
    'SELECT6': NBM_SELECT6,
    'SETU03': NBM_SETU03,
    'STAFF00': NBM_STAFF00,
    'STAFF01': NBM_STAFF01,
    'STAFF02': NBM_STAFF02,
    'STAFF03': NBM_STAFF03,
    'STAFF04': NBM_STAFF04,
    'STAFF05': NBM_STAFF05,
    'STAFF06': NBM_STAFF06,
    'STAFF07': NBM_STAFF07,
    'STAFF08': NBM_STAFF08,
    'STAFF09': NBM_STAFF09,
    'STAFF10': NBM_STAFF10,
    'STAFF11': NBM_STAFF11,
    'STAFF12': NBM_STAFF12,
    'TITLE': NBM_TITLE,
    'TITLE2': NBM_TITLE2,
    'TUTORIAL_00': NBM_TUTORIAL_00,
    'USA': NBM_USA,
    'WIRELESS_ON': NBM_WIRELESS_ON,
    'WIRELESS_STRENGTH_LEVEL_0_B': NBM_WIRELESS_STRENGTH_LEVEL_0_B,
    'WIRELESS_STRENGTH_LEVEL_0_W': NBM_WIRELESS_STRENGTH_LEVEL_0_W,
    'WIRELESS_STRENGTH_LEVEL_1_B': NBM_WIRELESS_STRENGTH_LEVEL_1_B,
    'WIRELESS_STRENGTH_LEVEL_1_W': NBM_WIRELESS_STRENGTH_LEVEL_1_W,
    'WIRELESS_STRENGTH_LEVEL_2_B': NBM_WIRELESS_STRENGTH_LEVEL_2_B,
    'WIRELESS_STRENGTH_LEVEL_2_W': NBM_WIRELESS_STRENGTH_LEVEL_2_W,
    'WIRELESS_STRENGTH_LEVEL_3_B': NBM_WIRELESS_STRENGTH_LEVEL_3_B,
    'WIRELESS_STRENGTH_LEVEL_3_W': NBM_WIRELESS_STRENGTH_LEVEL_3_W,
    'SELECT3_CLEAR_NORMAL': NBM_SELECT3_CLEAR_NORMAL,
    'SELECT3_RATE_NORMAL': NBM_SELECT3_RATE_NORMAL,
    'SELECT3_SE_VOLUME_NORMAL': NBM_SELECT3_SE_VOLUME_NORMAL,
    'SELECT3_CREDITS_NORMAL': NBM_SELECT3_CREDITS_NORMAL,
    'SELECT3_BGM_VOLUME_NORMAL': NBM_SELECT3_BGM_VOLUME_NORMAL,
    'SELECT1_N_0_NORMAL': NBM_SELECT1_N_0_NORMAL,
    'SELECT1_N_1_NORMAL': NBM_SELECT1_N_1_NORMAL,
    'SELECT1_N_2_NORMAL': NBM_SELECT1_N_2_NORMAL,
    'SELECT1_N_3_NORMAL': NBM_SELECT1_N_3_NORMAL,
    'SELECT1_N_4_NORMAL': NBM_SELECT1_N_4_NORMAL,
    'SELECT1_N_5_NORMAL': NBM_SELECT1_N_5_NORMAL,
    'SELECT1_N_6_NORMAL': NBM_SELECT1_N_6_NORMAL,
    'SELECT1_N_7_NORMAL': NBM_SELECT1_N_7_NORMAL,
    'SELECT1_N_8_NORMAL': NBM_SELECT1_N_8_NORMAL,
    'SELECT1_N_9_NORMAL': NBM_SELECT1_N_9_NORMAL,
    'SELECT1_N_0_SELECTED': NBM_SELECT1_N_0_SELECTED,
    'SELECT1_N_1_SELECTED': NBM_SELECT1_N_1_SELECTED,
    'SELECT1_N_2_SELECTED': NBM_SELECT1_N_2_SELECTED,
    'SELECT1_N_3_SELECTED': NBM_SELECT1_N_3_SELECTED,
    'SELECT1_N_4_SELECTED': NBM_SELECT1_N_4_SELECTED,
    'SELECT1_N_5_SELECTED': NBM_SELECT1_N_5_SELECTED,
    'SELECT1_N_6_SELECTED': NBM_SELECT1_N_6_SELECTED,
    'SELECT1_N_7_SELECTED': NBM_SELECT1_N_7_SELECTED,
    'SELECT1_N_8_SELECTED': NBM_SELECT1_N_8_SELECTED,
    'SELECT1_N_9_SELECTED': NBM_SELECT1_N_9_SELECTED,
    'SELECT1_START_NORMAL': NBM_SELECT1_START_NORMAL,
    'SELECT1_CLEARED_NORMAL': NBM_SELECT1_CLEARED_NORMAL,
    'SELECT1_RETURN_NORMAL': NBM_SELECT1_RETURN_NORMAL,
    'SELECT1_START_SELECTED': NBM_SELECT1_START_SELECTED,
    'SELECT1_CLEARED_SELECTED': NBM_SELECT1_CLEARED_SELECTED,
    'SELECT1_RETURN_SELECTED': NBM_SELECT1_RETURN_SELECTED,
    'SELECT1_DIFF_A_NORMAL': NBM_SELECT1_DIFF_A_NORMAL,
    'SELECT1_DIFF_B_NORMAL': NBM_SELECT1_DIFF_B_NORMAL,
    'SELECT1_DIFF_C_NORMAL': NBM_SELECT1_DIFF_C_NORMAL,
    'SELECT1_DIFF_D_NORMAL': NBM_SELECT1_DIFF_D_NORMAL,
    'SELECT1_DIFF_E_NORMAL': NBM_SELECT1_DIFF_E_NORMAL,
    'SELECT1_UP_NORMAL': NBM_SELECT1_UP_NORMAL,
    'SELECT1_UP_SELECTED': NBM_SELECT1_UP_SELECTED,
    'SELECT1_DOWN_NORMAL': NBM_SELECT1_DOWN_NORMAL,
    'SELECT1_DOWN_SELECTED': NBM_SELECT1_DOWN_SELECTED,
    'SELECT4_NUMBER_A': NBM_SELECT4_NUMBER_A,
    'SELECT4_PICTURE_A': NBM_SELECT4_PICTURE_A,
    'SELECT4_NUMBER_B': NBM_SELECT4_NUMBER_B,
    'SELECT4_PICTURE_B': NBM_SELECT4_PICTURE_B,
    'PAZL_SELECT2B_RETURN_NORMAL': NBM_PAZL_SELECT2B_RETURN_NORMAL,
    'PAZL_SELECT2B_RETURN_SELECTED': NBM_PAZL_SELECT2B_RETURN_SELECTED,
  };
  return map[constName];
}

/** Summary (total PNG bytes ≈ 236.43 KB). */
export const NBM_MANIFEST = { total: 42, totalBytes: 242109 };
