// AUTO-GENERATED by scripts/gen_nbm_assets_ts.py — DO NOT EDIT
// NBM decoded resources → miniprogram/assets/nbm PNG URLs

export const NBM_DOWNLOAD = '/assets/nbm/download.nbm.png';
export const NBM_DWLOGO = '/assets/nbm/dwlogo.nbm.png';
export const NBM_LICENSE = '/assets/nbm/license.nbm.png';
export const NBM_MENU_CSOL = '/assets/nbm/menu_csol.nbm.png';
export const NBM_NUMCLO_00 = '/assets/nbm/numclo_00.nbm.png';
export const NBM_NUMCLO_WAKU = '/assets/nbm/numclo_waku.nbm.png';
export const NBM_PAZL_SELECT = '/assets/nbm/pazl_select.nbm.png';
export const NBM_PAZL_SELECT2A = '/assets/nbm/pazl_select2a.nbm.png';
export const NBM_PAZL_SELECT2B = '/assets/nbm/pazl_select2b.nbm.png';
export const NBM_PAZL_SELECT2C = '/assets/nbm/pazl_select2c.nbm.png';
export const NBM_PAZL_YAJIRUSI = '/assets/nbm/pazl_yajirusi.nbm.png';
export const NBM_SELECT1 = '/assets/nbm/select1.nbm.png';
export const NBM_SELECT3 = '/assets/nbm/select3.nbm.png';
export const NBM_SELECT4 = '/assets/nbm/select4.nbm.png';
export const NBM_SELECT6 = '/assets/nbm/select6.nbm.png';
export const NBM_SETU03 = '/assets/nbm/setu03.nbm.png';
export const NBM_STAFF00 = '/assets/nbm/staff00.nbm.png';
export const NBM_STAFF01 = '/assets/nbm/staff01.nbm.png';
export const NBM_STAFF02 = '/assets/nbm/staff02.nbm.png';
export const NBM_STAFF03 = '/assets/nbm/staff03.nbm.png';
export const NBM_STAFF04 = '/assets/nbm/staff04.nbm.png';
export const NBM_STAFF05 = '/assets/nbm/staff05.nbm.png';
export const NBM_STAFF06 = '/assets/nbm/staff06.nbm.png';
export const NBM_STAFF07 = '/assets/nbm/staff07.nbm.png';
export const NBM_STAFF08 = '/assets/nbm/staff08.nbm.png';
export const NBM_STAFF09 = '/assets/nbm/staff09.nbm.png';
export const NBM_STAFF10 = '/assets/nbm/staff10.nbm.png';
export const NBM_STAFF11 = '/assets/nbm/staff11.nbm.png';
export const NBM_STAFF12 = '/assets/nbm/staff12.nbm.png';
export const NBM_TITLE = '/assets/nbm/title.nbm.png';
export const NBM_TITLE2 = '/assets/nbm/title2.nbm.png';
export const NBM_TUTORIAL_00 = '/assets/nbm/tutorial_00.nbm.png';
export const NBM_USA = '/assets/nbm/usa.nbm.png';
export const NBM_WIRELESS_ON = '/assets/nbm/wireless_on.nbm.png';
export const NBM_WIRELESS_STRENGTH_LEVEL_0_B = '/assets/nbm/wireless_strength_level_0_b.nbm.png';
export const NBM_WIRELESS_STRENGTH_LEVEL_0_W = '/assets/nbm/wireless_strength_level_0_w.nbm.png';
export const NBM_WIRELESS_STRENGTH_LEVEL_1_B = '/assets/nbm/wireless_strength_level_1_b.nbm.png';
export const NBM_WIRELESS_STRENGTH_LEVEL_1_W = '/assets/nbm/wireless_strength_level_1_w.nbm.png';
export const NBM_WIRELESS_STRENGTH_LEVEL_2_B = '/assets/nbm/wireless_strength_level_2_b.nbm.png';
export const NBM_WIRELESS_STRENGTH_LEVEL_2_W = '/assets/nbm/wireless_strength_level_2_w.nbm.png';
export const NBM_WIRELESS_STRENGTH_LEVEL_3_B = '/assets/nbm/wireless_strength_level_3_b.nbm.png';
export const NBM_WIRELESS_STRENGTH_LEVEL_3_W = '/assets/nbm/wireless_strength_level_3_w.nbm.png';

/** Full flat list of all 42 NBM assets. */
export const NBM_ALL = [
  NBM_DOWNLOAD,
  NBM_DWLOGO,
  NBM_LICENSE,
  NBM_MENU_CSOL,
  NBM_NUMCLO_00,
  NBM_NUMCLO_WAKU,
  NBM_PAZL_SELECT,
  NBM_PAZL_SELECT2A,
  NBM_PAZL_SELECT2B,
  NBM_PAZL_SELECT2C,
  NBM_PAZL_YAJIRUSI,
  NBM_SELECT1,
  NBM_SELECT3,
  NBM_SELECT4,
  NBM_SELECT6,
  NBM_SETU03,
  NBM_STAFF00,
  NBM_STAFF01,
  NBM_STAFF02,
  NBM_STAFF03,
  NBM_STAFF04,
  NBM_STAFF05,
  NBM_STAFF06,
  NBM_STAFF07,
  NBM_STAFF08,
  NBM_STAFF09,
  NBM_STAFF10,
  NBM_STAFF11,
  NBM_STAFF12,
  NBM_TITLE,
  NBM_TITLE2,
  NBM_TUTORIAL_00,
  NBM_USA,
  NBM_WIRELESS_ON,
  NBM_WIRELESS_STRENGTH_LEVEL_0_B,
  NBM_WIRELESS_STRENGTH_LEVEL_0_W,
  NBM_WIRELESS_STRENGTH_LEVEL_1_B,
  NBM_WIRELESS_STRENGTH_LEVEL_1_W,
  NBM_WIRELESS_STRENGTH_LEVEL_2_B,
  NBM_WIRELESS_STRENGTH_LEVEL_2_W,
  NBM_WIRELESS_STRENGTH_LEVEL_3_B,
  NBM_WIRELESS_STRENGTH_LEVEL_3_W,
];

/**
 * 模式资源归属（重要）:
 *  - Essential Sudoku DS = 数独 number puzzle, 题目数据来自 numple0-9.data.
 *  - numclo 系 / pazl 系 NBM 是图画谜题 picture puzzle 模式的资源（另一种玩法,
 *    1:1 还原目标下必须接入, 不是弃用资源; V0.15.2 "wrong format" 标注已修正）.
 *  - 数独界面禁止引用 PICTURE_PUZZLE 组资源; 该组资源专供 picture puzzle 玩法界面.
 */

/** 数独模式通用 UI 资源 (菜单/设置/教程/下载/许可/地区). */
export const NBM_GROUP_MISC = [
  NBM_DOWNLOAD,
  NBM_DWLOGO,
  NBM_LICENSE,
  NBM_MENU_CSOL,
  NBM_SETU03,
  NBM_TUTORIAL_00,
  NBM_USA,
];

/** 图画谜题 (picture puzzle) 模式资源 — 数独界面禁用. */
export const NBM_GROUP_PICTURE_PUZZLE = [
  NBM_NUMCLO_00,
  NBM_NUMCLO_WAKU,
  NBM_PAZL_SELECT,
  NBM_PAZL_SELECT2A,
  NBM_PAZL_SELECT2B,
  NBM_PAZL_SELECT2C,
  NBM_PAZL_YAJIRUSI,
];

/** 数独模式选择界面按钮 (select1/3/4/6). */
export const NBM_GROUP_MENU_SELECT = [
  NBM_SELECT1,
  NBM_SELECT3,
  NBM_SELECT4,
  NBM_SELECT6,
];

export const NBM_GROUP_STAFF = [
  NBM_STAFF00,
  NBM_STAFF01,
  NBM_STAFF02,
  NBM_STAFF03,
  NBM_STAFF04,
  NBM_STAFF05,
  NBM_STAFF06,
  NBM_STAFF07,
  NBM_STAFF08,
  NBM_STAFF09,
  NBM_STAFF10,
  NBM_STAFF11,
  NBM_STAFF12,
];

export const NBM_GROUP_TITLE = [
  NBM_TITLE,
  NBM_TITLE2,
];

export const NBM_GROUP_WIRELESS = [
  NBM_WIRELESS_ON,
  NBM_WIRELESS_STRENGTH_LEVEL_0_B,
  NBM_WIRELESS_STRENGTH_LEVEL_0_W,
  NBM_WIRELESS_STRENGTH_LEVEL_1_B,
  NBM_WIRELESS_STRENGTH_LEVEL_1_W,
  NBM_WIRELESS_STRENGTH_LEVEL_2_B,
  NBM_WIRELESS_STRENGTH_LEVEL_2_W,
  NBM_WIRELESS_STRENGTH_LEVEL_3_B,
  NBM_WIRELESS_STRENGTH_LEVEL_3_W,
];


/** Resolve an NBM asset URL by its decoded name (without .nbm.bmp/.nbm.png extension). */
export function nbmUrl(name: string): string | undefined {
  const constName = `NBM_${name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/\.nbm$/i, "").toUpperCase()}`;
  const map: Record<string, string> = {
    'DOWNLOAD': NBM_DOWNLOAD,
    'DWLOGO': NBM_DWLOGO,
    'LICENSE': NBM_LICENSE,
    'MENU_CSOL': NBM_MENU_CSOL,
    'NUMCLO_00': NBM_NUMCLO_00,
    'NUMCLO_WAKU': NBM_NUMCLO_WAKU,
    'PAZL_SELECT': NBM_PAZL_SELECT,
    'PAZL_SELECT2A': NBM_PAZL_SELECT2A,
    'PAZL_SELECT2B': NBM_PAZL_SELECT2B,
    'PAZL_SELECT2C': NBM_PAZL_SELECT2C,
    'PAZL_YAJIRUSI': NBM_PAZL_YAJIRUSI,
    'SELECT1': NBM_SELECT1,
    'SELECT3': NBM_SELECT3,
    'SELECT4': NBM_SELECT4,
    'SELECT6': NBM_SELECT6,
    'SETU03': NBM_SETU03,
    'STAFF00': NBM_STAFF00,
    'STAFF01': NBM_STAFF01,
    'STAFF02': NBM_STAFF02,
    'STAFF03': NBM_STAFF03,
    'STAFF04': NBM_STAFF04,
    'STAFF05': NBM_STAFF05,
    'STAFF06': NBM_STAFF06,
    'STAFF07': NBM_STAFF07,
    'STAFF08': NBM_STAFF08,
    'STAFF09': NBM_STAFF09,
    'STAFF10': NBM_STAFF10,
    'STAFF11': NBM_STAFF11,
    'STAFF12': NBM_STAFF12,
    'TITLE': NBM_TITLE,
    'TITLE2': NBM_TITLE2,
    'TUTORIAL_00': NBM_TUTORIAL_00,
    'USA': NBM_USA,
    'WIRELESS_ON': NBM_WIRELESS_ON,
    'WIRELESS_STRENGTH_LEVEL_0_B': NBM_WIRELESS_STRENGTH_LEVEL_0_B,
    'WIRELESS_STRENGTH_LEVEL_0_W': NBM_WIRELESS_STRENGTH_LEVEL_0_W,
    'WIRELESS_STRENGTH_LEVEL_1_B': NBM_WIRELESS_STRENGTH_LEVEL_1_B,
    'WIRELESS_STRENGTH_LEVEL_1_W': NBM_WIRELESS_STRENGTH_LEVEL_1_W,
    'WIRELESS_STRENGTH_LEVEL_2_B': NBM_WIRELESS_STRENGTH_LEVEL_2_B,
    'WIRELESS_STRENGTH_LEVEL_2_W': NBM_WIRELESS_STRENGTH_LEVEL_2_W,
    'WIRELESS_STRENGTH_LEVEL_3_B': NBM_WIRELESS_STRENGTH_LEVEL_3_B,
    'WIRELESS_STRENGTH_LEVEL_3_W': NBM_WIRELESS_STRENGTH_LEVEL_3_W,
  };
  return map[constName];
}

/** Summary (total PNG bytes ≈ 241.46 KB). */
export const NBM_MANIFEST = { total: 42, totalBytes: 247251 };
