/**
 * utils/sudoku/numclo_answers.ts — Answer names for numclo0-9 (Picture Logic).
 *
 * 双语名表 (同一模块文件, 避免新增模块文件导致小程序增量编译未收录):
 * - NUMCLO_ANSWERS    : ROM numclo_seikaiNN.dat 内 ASCII 英文名 (每类 100 题)
 * - NUMCLO_ANSWERS_ZH : 人工翻译中文名 (与英文表逐索引对齐, 共 1000 条)
 * numclo_00-03 / numclo_tu (附加/教程) 无正规名字表, 由入口层兜底类别 label。
 */

export const NUMCLO_ANSWERS: Record<string, string[]> = {
  'numclo0.data': ["Crab", "Cat", "Raccoon Dog", "Pig", "Rabbit", "Crow", "Ladybug", "Whale", "Pelican", "Chameleon", "Tropical Fish", "Fox", "Penguin", "Rooster", "Ostrich", "Ray", "Clione", "Snail", "Owl", "Panda", "Catfish", "Sea Horse", "Bat", "Dog", "Camel", "Goat", "Tiger", "Sheep", "Pigeon", "Dolphin", "Bee", "Praying Mantis", "Tapir", "Sunfish", "Squirrel", "Jellyfish", "Wild boar", "Koala Bear", "Cow", "Zebra", "Carp", "Swan", "Angler Fish", "Sea Gull", "Spider", "Ferret", "Kiwi", "Crane", "Stag Beetle", "Butterfly", "Flamingo", "Monkey", "Lizard", "Turtle", "Seal", "Bear", "Racer Panda", "Crayfish", "Horse", "Snake", "Mole", "Killer Whale", "Loch Ness Monster", "Kangaroo", "Elephant", "Cobra", "Peacock", "Cockatiel", "Spearfish", "Nautilus", "Caterpillar", "Flying Squirrel", "Hermit Crab", "Sea Otter", "Harbour Seal", "Armadillo", "Turkey", "Panther", "Hamster", "Scorpion", "Rhinoceros", "Beetle", "Mouse", "Locust", "Giraffe", "Beaver", "Deer", "Frog", "Crocodile", "Gorilla", "Hippopotamus", "Lion", "Octopus", "Skunk", "Squid", "Coelacanth", "Eel", "Jewel Beetle", "Sea Anemone", "Puffer Fish"],
  'numclo1.data': ["Triangular Flask", "Magnet", "Bottle of Medicine", "red blood cell", "Polyethylene Tank", "Test Tube", "Alcohol Lamp", "Nurse Cap", "Globe", "Miniature Bulb", "Molecule Model", "Round Flask", "Thermometer", "Pearl", "Amber", "Medical Pill", "Milk Bowl", "Diode", "Eye Drops", "Daphnia", "Ruby", "Onyx", "Chromosome", "Weight", "Prism", "Superconductor", "Amoeba", "Rocket Engine", "Bandage", "Diamond", "Semiconductor", "Radiation Diode", "Laser", "Malachite", "Cell", "Infusion Liquid", "Voltmeter", "Petri Dish", "Formalin Dip", "Constellation Chart", "Gas Burner", "Met cylinder", "Crucible", "Euglena", "Litmus Paper", "Pipette", "Ampoule", "Microscope", "Fossil", "Frog Anatomy", "Scalpel", "Wrought Iron", "Tripod", "Grain", "Crystal", "Vacuum Tube", "Jet Engine", "hand dynamometer", "Injection Syringe", "Gastrocamera", "Pinset", "Test Tube Brush", "Closterium", "Eye Patch", "Engine", "Branched Flask", "Solar Battery", "Calendar Clock", "Gold", "Robot", "Scale", "Powdered Medicine", "Compass", "Stethoscope", "Lay Figure", "Stevenson Screen", "Motor", "Lapis Lazuli", "Static Electricity", "Mask", "Plasma Light", "Crutch", "Plaster", "Thermometer", "Stretcher", "Doctor", "Radio Wave", "Water Pillow", "Ice Bag", "Tube Medicine", "Safety Glasses", "Oxygen Tank", "Skeleton specimen", "Sapphire", "Emerald", "Bathroom Scale", "Split Cell", "Paramecium", "T2 Bacteriophage", "Brain Cell"],
  'numclo2.data': ["Shinto Gateway", "Maple Leaf", "Arc de Triomphe", "Tent", "Ear of Rice", "Hibiscus", "Mt. Fuji", "Pyramid", "Palm Tree", "Post Box", "Building", "Silo", "Ancient Tomb", "Chrysanthemum", "Iris", "Acorn", "Bungee Cord", "Windmill", "The Parthenon", "Japanese Bellflower", "Japan", "Italy", "Factory", "Ginkgo", "U.S.A.", "Clover", "Utsubo-Kazura", "bridge", "New Zealand", "Pinecone", "Valley Lily", "Lighthouse", "Moai Statue", "Aquadukt", "Hydrangea", "Tokyo Tower", "Western Castle", "Japanese Castle", "Dandelion", "Control Tower", "Pine Needle", "Wind Generator", "Cosmos", "Cherry Blossom", "Pachira", "Cedar", "Rafflesia", "Ayers Rock", "Sphinx", "Mt. Everest", "Five-Storied Pagoda", "Australia", "Africa", "Fern", "Totem Pole", "Mosque", "Butterbur", "Observatory", "Coliseum", "Obelisk", "kind of a sunflower", "Leaning Tower of Pisa", "Cotyledon", "Treble Clef", "Lily", "Rose", "Flytrap", "Empire State Building", "Opera House", "Greenhouse", "Lotus Blossom", "Parabolic Antenna", "Morning Glory", "Statue of Buddha", "Bamboo", "Stonehenge", "Brooklyn Bridge", "Big Ben", "Domed stadium", "Savannah", "Petrol Tank", "Taj Mahal", "Tsutenkaku", "Birch Leaf", "Thatched Roof", "Lavender", "Oil Field", "Bulb", "Rape Blossoms", "Wind Measure", "Strychia", "Bellflower", "Skunk Cabbage", "Ivy", "Camellia", "Grand Canyon", "Circus Tent", "Templo de la Sagrada Familia", "Fox Face", "Poinsettia"],
  'numclo3.data': ["TV set", "Telephone", "Sewing Machine", "Dryer", "Cell Phone", "Spoon of earthenware", "Alarm Clock", "Heart Mark", "Trophy", "Plastic Bucket", "Rest room mark", "Spark Mark", "Dharma Doll", "Teacup", "Pencil", "Radio", "Trumpet", "Triangle", "Castanet", "Maracas", "Seat Belt Mark", "Video Camera", "Digital Camera", "Headphones", "Refrigerator", "Piano", "Long Silk Hat", "Keyboard Harmonica", "Harmonica", "Horn", "Tambourine", "Cymbal", "Snare drum", "Electric Guitar", "Accordion", "Metronome", "Ocarina", "Saxophone", "Conga", "Eraser", "Fountain Pen", "Match", "Kettle", "Cutter", "Scotch Tape", "Stapler", "Wind Bell", "Tissue Paper", "Stamp", "sandglass", "Desktop Computer", "Lantern", "Violin", "Shamisen", "Wadaiko", "Combination CD Player", "Floppy Disk", "Sprayer", "CPU", "Laptop Computer", "Lightning Mark", "Mixer", "Washing Machine", "Coffee Maker", "Microwave oven", "Electronic Toothbrush", "Fan", "Soy Sauce Dispenser", "Toaster", "Vacuum Cleaner", "Flashlight", "Pot", "Massage Chair", "Iron", "Lamp", "Cello", "Memo Pad", "Lighter", "Crossing", "Eyeglasses", "Astronomical Telescope", "Christmas Tree", "Hat", "C Clef", "Bell", "Binoculars", "Letter Box", "Diamond Ring", "Umbrella", "Wristwatch", "Paint", "Crown", "Crackers", "Footprints", "Balloon", "Chair", "Bass Clef", "Semibreve", "Magnifying Glass", "Vending Machine"],
  'numclo4.data': ["Spade", "Half Note", "Loudspeaker", "Mosquito Coil", "Metal Dumbbells", "Bow  Arrow", "Expander", "Cactus", "Yoyo", "Dragonfly", "Kendama", "Hammer", "plane", "chisel", "Clothespin", "Quarter Note", "Annual Ring", "Bomb", "Flats", "slingshot", "Roller", "Broom", "Eighth Note", "Canvas", "Paint", "Sixteenth Note", "horsetail", "Quarter Rest", "Pinwheel", "Kite Flying", "Silhouette", "Doll Festival", "cherry blossom viewing", "carp streamer", "Helmet", "Alien", "TeruTeru Bozu", "Goldfish", "the Star Festival", "Ghost", "Question Mark", "Rabbit in the Moon", "Halloween", "Fallen Leaf", "Santa Claus", "Christmas Decorations", "Candle", "Snowman", "Diamond", "Ogre", "Ammonite", "Trilobite", "Anomalocaris", "Hallucigenia", "Opabinia", "Apatosaurus", "Allosaurus", "Stegosaurus", "Triceratops", "Water Pistol", "top", "Teddy Bear", "Tin Robot", "Clatter", "Crane game", "Building Blocks", "Rattle", "Rattling Lottery", "dirk", "Katana Sword", "Armour", "Axe", "Nunchaks", "Arrow", "Lantern", "Fortune Slip", "Street Lamp", "Cannon", "Matchlock", "Fish Bowl", "Phone Booth", "iron bar", "Swing", "Chainsaw", "Boxing Ropes", "Stove", "adhesive tape", "Drill", "Radio-Controlled Toy", "Hand Grip", "2-Person Bucksaw", "Eiffel Tower", "Rubber Dinghy", "Dragon", "Manganese Bulb", "Boomerang", "Jack-o-Lantern", "Vase with Flower", "Beachball", "Fireworks"],
  'numclo5.data': ["crescent", "half-moon", "Full Moon", "Star", "Big Dipper", "Water", "Fire", "Mountain", "Wood", "River", "Waterfall", "hoe", "Plow", "Lake", "Sea", "Sickle", "Rain", "Forest", "Mars", "Earth", "Domino", "Paper", "Stone", "Scissor", "Bubble", "Circle of Wisdom", "Goldfish-Catching", "Paper Airplane", "Amitabha Slip", "Martian", "Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra", "Scorpion", "Sagittarius", "Capricorn", "Aquarius", "Pisces", "Spring", "Summer", "Fall", "Winter", "Field", "Morning", "Evening", "Night", "Bowling", "Cards", "Video Game", "Mah-jong", "Orion", "Cassiopeia", "Puzzle", "Frisbee", "Sun", "Jump Rope", "String Telephone", "Treasure Map", "Slot", "Seesaw", "Cloud", "Building Block", "Multistage Rocket", "Satellite", "Pinball", "Bat", "Solar System", "Planet", "Comet", "Rainbow", "Rising Sun", "Hot Spring", "Moon Landing", "Dice", "Othello", "Jungle Gym", "Bug collecting", "snowball fight", "Ball", "Slide", "Merry-go-Round", "Soccer Ball", "Swimming Pool", "Hula Hoop", "Colour Book", "sled", "Coffee Cup", "Roulette", "Pawn", "Rook", "Bishop", "Knight", "Queen", "King", "Foot Race", "Galaxy"],
  'numclo6.data': ["Stamp", "Helicopter", "Spanner", "UFO", "Unicycle", "House", "Skateboard", "Cheap Lighter", "playground equipment", "Wastebasket", "Pin", "Tack", "Tyre", "Yumbo", "Necklace", "lion dance", "Tractor", "Jet-Ski", "Pincers", "Light Truck", "Wrench", "Hovercraft", "Linear Motor Car", "Scale Triangular Ruler", "Tricycle", "Pipe", "Jeep", "Tanker", "Formula Car", "Baby Car", "Train", "Road Roller", "Old Fighter Aircraft", "Pencil Sharpener", "Monorail", "46-Ton Dump Truck", "16th Rest", "Belt", "Eighth Rest", "Fire Truck", "Hopping", "Convertible", "Ladder Car", "Sharp", "Ropeway", "Bicycle", "Crane vehicle", "High-Altitude Vehicle", "Steam Train", "Pedal Boat", "Mug", "Space Shuttle", "Ferris Wheel", "Glove", "Hair Clip", "Compass", "Screw", "Cattle Truck", "Mirror", "Truck", "Warship", "Bike", "Kickboard", "Lorry", "Scooter", "Ferry", "Ambulance", "Blimp", "Fishing Boat", "Paraglider", "Sailboat", "Lumberyard", "Bus", "Airship", "Passenger Boat", "Submarine", "Bullet Train", "Passenger Plane", "small box", "Brooch", "Bracelet", "Snowmobile", "Carriage", "Tank", "Bulldozer", "Streetcar", "Cement Truck", "Fighter Aircraft", "Cart", "Double-Decker Bus", "Haniwa", "Airplane", "Photo Frame", "Ashtray", "Rickshaw", "Yacht", "Beach Umbrella", "Stilt", "Hammock", "Parasailing"],
  'numclo7.data': ["Rice Ball", "Lemon", "Green Pepper", "Garlic", "Mushroom", "Cheese", "round rice-cake", "Ice-Cream Cone", "Chestnut", "Bamboo Shoot", "Pineapple", "Cayenne", "Corn", "Pumpkin", "Pear", "Japanese Radish", "Chinese Cabbage", "Apple", "Candy", "Radish", "Candy", "Chocolate Doughnuts", "Cherry", "Eggplant", "Broccoli", "Pudding", "Banana", "Fried prawns", "Soda", "Curry", "Rice Omelette", "Watermelon", "Onion", "Okra", "tube-shaped fish paste cake", "Green soybeans", "Sweet Potato", "Chocolate Bar", "Cucumber", "Oden", "Seaweed", "Cabbage", "Ice-Cream Stick", "Bread", "French Bread", "Jell-o", "Whole-Fried Chicken", "Fried Egg", "Turban Shell", "French Fries", "Shrimp", "Muscat", "Fish Bone", "Melon", "Carrot", "White Wine Red Wine", "Croissant", "Japanese Sherbet", "Milk Carton", "Asparagus", "Sandwich", "Hamburger", "Hot-Dog", "Hotcakes", "Spaghetti Bolognese", "Potato Chips", "Sushi", "Snack", "Pizza", "Meat Bun", "Sundae", "Sukiyaki", "Takoyaki", "Frankfurter", "Cream Soda", "Ramen", "Stuffed Cabbage", "Gyoza", "Spiced Lotus Root", "Hamburger Steak", "Happy Meal", "Taiyaki", "Fried Rice", "Cream Puffs", "Bream", "Matsutake Mushroom", "Peach", "Wieners", "Strawberry Jam", "Bracken", "Crepe", "Cookies", "Okonomiyaki", "Tofu", "Beer", "Yakitori", "Strawberry Shortcake", "Shrimp Roll", "Meat Dumpling", "Mixed Salad"],
  'numclo8.data': ["Hanger", "Letter", "Swimsuit", "Teacup", "Key", "Cigarettes", "Student bag", "Golf", "Knife Fork", "Lipstick", "Fire Extinguisher", "Hairband", "Ping Pong", "Lock", "Pool", "CD", "Asian Comb", "Chopsticks", "skating", "Notebook", "Videotape", "Football", "Carving Knife", "Watering pot", "Wave", "Dolphin", "Helmet", "Scissors", "Traffic Light", "Toilet Paper", "Shovel", "Table", "Clip", "Brush", "Basket", "Projector", "Scroll", "Slipper", "satchel", "High Heels", "Wrestling Ring", "Spray Can", "Darts", "Toothpaste", "Clothes", "Snowboard", "Parachute", "Canoe", "Rubber Stamp", "Bottle Opener", "Walk", "Run", "Push-Ups", "Abdomen", "Baseball", "Tennis", "Jump-Rope", "Weight-Lifting", "Hurdles", "Relay", "Long Jump", "Fencing", "horizontal bar", "Volleyball", "Karate", "Karaoke", "Yoga", "Rhythmic Gymnastics", "Bicycle race", "Horse-Racing", "Skiing", "Surfing", "Swimming", "Synchronized Swimming", "Rugby", "Pro-Wrestling", "Vaulting", "Badminton", "Judo", "Boxing", "Motorboat Racing", "Dancing", "Tug-of-War", "High Jump", "Rock Climbing", "Sailing", "Diving", "Soap", "Mitten", "Shrine maiden clothes", "Pillow", "Mattress", "Hand Soap", "Turner", "Pot", "Waitress Outfit", "Ladle", "Sponge", "Towel", "Earpick"],
  'numclo9.data': ["Plus", "Minus", "Divide", "Apron", "Equal", "Square", "Circle", "Triangle", "Plus-Minus", "Rectangle", "Percent", "Height Scale", "Less Than", "(Number Symbol: Therefore)", "(Number Symbol: Because)", "Pi", "Sigma", "Theta", "Arrow", "Omega", "Night View", "Root", "Greater Than Equal", "Less Than Equal", "Not Equal", "(Number Symbol: during ...)", "Integral", "Phi", "Hexagon", "Isosceles Triangle", "Times", "Pill Bag", "Clipper", "Nipper", "Hot Spring Mark", "Safety Helmet", "Gargle", "Advertising Blimp", "Cardiogram", "Bathroom", "Cavity", "Greater Than", "Anthill", "Good Teeth", "Stomach", "Eye", "Nose", "Heart", "Mouth", "Ear", "X-Ray", "Bees' Nest", "Leg", "Arm", "Bone", "Bad Teeth", "Healthy Teeth", "Wristband", "Socks", "One-Piece Dress", "Jeans", "Sweatpants", "Tanktop", "Muffler", "Sweater", "Boots", "Mule", "High-Cut Sneaker", "Button", "Casket", "Ponytail", "Cold", "Gentleman's Shoes", "Sneakers", "Handkerchief", "Nail", "Knit Cap", "Beaker", "Anklet", "Massage", "Compact", "Pyjamas", "Knapsack", "Earring", "Silk Hat", "Contact Lenses", "Hair Remover", "Nail File", "Nail Clipper", "Poultice", "Trouble", "Manometer", "Skirt", "Knitting Fabric", "Perfume", "Necktie", "Beret", "Knee Injury", "Braid", "Pie Chart"],
};

/**
 * NUMCLO_ANSWERS_ZH — 图画谜题答案中文名 (人工翻译, 与 NUMCLO_ANSWERS 逐索引对齐)。
 * 优先级: 有中文名 -> 用中文; 无该 file/index 条目 -> 画面回退到「类别中文 label」。
 */
export const NUMCLO_ANSWERS_ZH: Record<string, string[]> = {
  'numclo0.data': [
    '螃蟹', '猫', '貉', '猪', '兔子', '乌鸦', '瓢虫', '鲸', '鹈鹕', '变色龙',
    '热带鱼', '狐狸', '企鹅', '公鸡', '鸵鸟', '鳐鱼', '冰海天使', '蜗牛', '猫头鹰', '熊猫',
    '鲶鱼', '海马', '蝙蝠', '狗', '骆驼', '山羊', '老虎', '绵羊', '鸽子', '海豚',
    '蜜蜂', '螳螂', '貘', '翻车鱼', '松鼠', '水母', '野猪', '考拉', '奶牛', '斑马',
    '鲤鱼', '天鹅', '鮟鱇鱼', '海鸥', '蜘蛛', '雪貂', '几维鸟', '鹤', '锹甲虫', '蝴蝶',
    '火烈鸟', '猴子', '蜥蜴', '乌龟', '海豹', '熊', '浣熊', '小龙虾', '马', '蛇',
    '鼹鼠', '虎鲸', '尼斯湖水怪', '袋鼠', '大象', '眼镜蛇', '孔雀', '玄凤鹦鹉', '旗鱼', '鹦鹉螺',
    '毛毛虫', '鼯鼠', '寄居蟹', '海獭', '斑海豹', '犰狳', '火鸡', '豹', '仓鼠', '蝎子',
    '犀牛', '甲虫', '老鼠', '蝗虫', '长颈鹿', '河狸', '鹿', '青蛙', '鳄鱼', '大猩猩',
    '河马', '狮子', '章鱼', '臭鼬', '鱿鱼', '腔棘鱼', '鳗鱼', '吉丁虫', '海葵', '河豚',
  ],
  'numclo1.data': [
    '锥形烧瓶', '磁铁', '药瓶', '红细胞', '聚乙烯水槽', '试管', '酒精灯', '护士帽', '地球仪', '小灯泡',
    '分子模型', '圆底烧瓶', '温度计', '珍珠', '琥珀', '药片', '牛奶碗', '二极管', '眼药水', '水蚤',
    '红宝石', '缟玛瑙', '染色体', '砝码', '棱镜', '超导体', '阿米巴变形虫', '火箭发动机', '绷带', '钻石',
    '半导体', '发光二极管', '激光器', '孔雀石', '细胞', '点滴输液', '电压表', '培养皿', '福尔马林标本', '星座图',
    '煤气灯', '量筒', '坩埚', '眼虫', '石蕊试纸', '移液管', '安瓿瓶', '显微镜', '化石', '青蛙解剖',
    '手术刀', '熟铁', '三脚架', '晶粒', '晶体', '真空管', '喷气发动机', '握力计', '注射器', '胃镜相机',
    '镊子', '试管刷', '新月藻', '眼罩', '引擎', '支管烧瓶', '太阳能电池', '日历钟', '黄金', '机器人',
    '天平', '药粉', '指南针', '听诊器', '人体模型', '百叶箱', '电动机', '青金石', '静电', '面具',
    '等离子灯', '拐杖', '石膏', '体温计', '担架', '医生', '电波', '水枕', '冰袋', '管装药膏',
    '护目镜', '氧气瓶', '骨骼标本', '蓝宝石', '祖母绿', '体重秤', '分裂细胞', '草履虫', 'T2噬菌体', '脑细胞',
  ],
  'numclo2.data': [
    '鸟居', '枫叶', '凯旋门', '帐篷', '稻穗', '木槿', '富士山', '金字塔', '棕榈树', '邮筒',
    '大楼', '筒仓', '古坟', '菊花', '鸢尾花', '橡果', '蹦极', '风车', '帕特农神庙', '桔梗',
    '日本', '意大利', '工厂', '银杏', '美国', '三叶草', '空木葛', '桥', '新西兰', '松果',
    '铃兰', '灯塔', '摩艾石像', '渡槽', '绣球花', '东京塔', '西式城堡', '日本城堡', '蒲公英', '管制塔',
    '松针', '风力发电机', '大波斯菊', '樱花', '马拉巴栗', '雪松', '大王花', '艾尔斯岩', '狮身人面像', '珠穆朗玛峰',
    '五重塔', '澳大利亚', '非洲', '蕨类', '图腾柱', '清真寺', '蜂斗菜', '天文台', '斗兽场', '方尖碑',
    '向日葵', '比萨斜塔', '子叶', '高音谱号', '百合', '玫瑰', '捕蝇草', '帝国大厦', '歌剧院', '温室',
    '莲花', '抛物面天线', '牵牛花', '佛像', '竹子', '巨石阵', '布鲁克林大桥', '大本钟', '圆顶体育馆', '热带草原',
    '油罐', '泰姬陵', '通天阁', '白桦叶', '茅草屋', '薰衣草', '油田', '鳞茎', '油菜花', '风速计',
    '鹤望兰', '风铃草', '水芭蕉', '常春藤', '山茶花', '大峡谷', '马戏团帐篷', '圣家堂', '狐狸脸', '一品红',
  ],
  'numclo3.data': [
    '电视机', '电话', '缝纫机', '烘干机', '手机', '陶勺', '闹钟', '心形标记', '奖杯', '塑料桶',
    '洗手间标志', '闪电标志', '达摩不倒翁', '茶杯', '铅笔', '收音机', '小号', '三角铁', '响板', '沙锤',
    '安全带标志', '摄像机', '数码相机', '头戴耳机', '冰箱', '钢琴', '高筒礼帽', '键盘口琴', '口琴', '圆号',
    '铃鼓', '钹', '小军鼓', '电吉他', '手风琴', '节拍器', '陶笛', '萨克斯', '康加鼓', '橡皮擦',
    '钢笔', '火柴', '烧水壶', '美工刀', '透明胶带', '订书机', '风铃', '纸巾', '邮票', '沙漏',
    '台式电脑', '灯笼', '小提琴', '三味线', '和太鼓', '组合音响', '软盘', '喷雾器', 'CPU', '笔记本电脑',
    '雷电标志', '搅拌机', '洗衣机', '咖啡机', '微波炉', '电动牙刷', '电风扇', '酱油瓶', '烤面包机', '吸尘器',
    '手电筒', '锅', '按摩椅', '熨斗', '台灯', '大提琴', '便签本', '打火机', '人行横道', '眼镜',
    '天文望远镜', '圣诞树', '帽子', '中音谱号', '铃', '双筒望远镜', '邮筒', '钻戒', '伞', '手表',
    '颜料', '皇冠', '拉炮', '脚印', '气球', '椅子', '低音谱号', '全音符', '放大镜', '自动售货机',
  ],
  'numclo4.data': [
    '黑桃', '二分音符', '扩音器', '蚊香', '哑铃', '弓箭', '拉力器', '仙人掌', '悠悠球', '蜻蜓',
    '剑玉', '锤子', '刨子', '凿子', '晾衣夹', '四分音符', '年轮', '炸弹', '降号', '弹弓',
    '滚筒', '扫帚', '八分音符', '画布', '颜料', '十六分音符', '笔头菜', '四分休止符', '纸风车', '放风筝',
    '剪影', '女儿节', '赏花', '鲤鱼旗', '头盔', '外星人', '晴天娃娃', '金鱼', '七夕', '幽灵',
    '问号', '月兔', '万圣节', '落叶', '圣诞老人', '圣诞装饰', '蜡烛', '雪人', '方块', '鬼怪',
    '菊石', '三叶虫', '奇虾', '怪诞虫', '奥帕宾虫', '迷惑龙', '异特龙', '剑龙', '三角龙', '水枪',
    '陀螺', '泰迪熊', '铁皮机器人', '拨浪鼓', '抓娃娃机', '积木', '摇铃', '抽签筒', '短剑', '日本刀',
    '铠甲', '斧头', '双节棍', '箭', '灯笼', '御神签', '街灯', '大炮', '火绳枪', '鱼缸',
    '电话亭', '铁棒', '秋千', '电锯', '拳击绳圈', '暖炉', '胶带', '电钻', '遥控玩具', '握力器',
    '双人锯', '埃菲尔铁塔', '橡皮艇', '龙', '锰灯泡', '回力镖', '南瓜灯', '插花花瓶', '沙滩球', '烟花',
  ],
  'numclo5.data': [
    '新月', '半月', '满月', '星星', '北斗七星', '水', '火', '山', '木', '河',
    '瀑布', '锄头', '犁', '湖', '海', '镰刀', '雨', '森林', '火星', '地球',
    '多米诺', '纸', '石头', '剪刀', '泡泡', '智慧环', '捞金鱼', '纸飞机', '阿弥陀签', '火星人',
    '白羊座', '金牛座', '双子座', '巨蟹座', '狮子座', '处女座', '天秤座', '天蝎座', '射手座', '摩羯座',
    '水瓶座', '双鱼座', '春', '夏', '秋', '冬', '田野', '早晨', '傍晚', '夜晚',
    '保龄球', '扑克牌', '电子游戏', '麻将', '猎户座', '仙后座', '拼图', '飞盘', '太阳', '跳绳',
    '纸杯电话', '藏宝图', '老虎机', '跷跷板', '云', '积木', '多级火箭', '人造卫星', '弹珠机', '棒球棒',
    '太阳系', '行星', '彗星', '彩虹', '旭日', '温泉', '登月', '骰子', '黑白棋', '攀爬架',
    '捕虫', '打雪仗', '球', '滑梯', '旋转木马', '足球', '游泳池', '呼啦圈', '涂色书', '雪橇',
    '咖啡杯', '轮盘', '兵', '车', '象', '马', '后', '王', '赛跑', '银河',
  ],
  'numclo6.data': [
    '邮票', '直升机', '扳手', '飞碟', '独轮车', '房子', '滑板', '打火机', '游乐设施', '废纸篓',
    '别针', '图钉', '轮胎', '尤波车', '项链', '舞狮', '拖拉机', '水上摩托', '钳子', '轻型卡车',
    '活动扳手', '气垫船', '磁悬浮列车', '比例三角板', '三轮车', '管子', '吉普车', '油罐车', '方程式赛车', '婴儿车',
    '火车', '压路机', '旧式战斗机', '卷笔刀', '单轨列车', '46吨自卸卡车', '十六分休止符', '腰带', '八分休止符', '消防车',
    '跳跳球', '敞篷车', '云梯车', '升号', '缆车', '自行车', '吊车', '高空作业车', '蒸汽火车', '脚踏船',
    '马克杯', '航天飞机', '摩天轮', '手套', '发夹', '圆规', '螺丝', '牲畜运输车', '镜子', '卡车',
    '军舰', '摩托车', '滑板车', '重型货车', '小绵羊', '渡轮', '救护车', '飞艇', '渔船', '滑翔伞',
    '帆船', '贮木场', '巴士', '飞船', '客船', '潜水艇', '新干线', '客机', '小盒子', '胸针',
    '手链', '雪地摩托', '马车', '坦克', '推土机', '有轨电车', '水泥搅拌车', '战斗机', '手推车', '双层巴士',
    '埴轮', '飞机', '相框', '烟灰缸', '人力车', '游艇', '沙滩伞', '高跷', '吊床', '帆伞',
  ],
  'numclo7.data': [
    '饭团', '柠檬', '青椒', '大蒜', '蘑菇', '奶酪', '年糕', '甜筒冰淇淋', '栗子', '竹笋',
    '菠萝', '辣椒', '玉米', '南瓜', '梨', '白萝卜', '大白菜', '苹果', '糖果', '樱桃萝卜',
    '糖果', '巧克力甜甜圈', '樱桃', '茄子', '西兰花', '布丁', '香蕉', '炸虾', '汽水', '咖喱',
    '蛋包饭', '西瓜', '洋葱', '秋葵', '筒状鱼糕', '毛豆', '红薯', '巧克力棒', '黄瓜', '关东煮',
    '海苔', '卷心菜', '冰棍', '面包', '法棍', '果冻', '炸全鸡', '煎蛋', '角螺', '薯条',
    '虾', '麝香葡萄', '鱼骨', '哈密瓜', '胡萝卜', '红白酒', '可颂', '果子露', '牛奶盒', '芦笋',
    '三明治', '汉堡包', '热狗', '热香饼', '肉酱意面', '薯片', '寿司', '零食', '披萨', '肉包子',
    '圣代', '寿喜烧', '章鱼烧', '法兰克福肠', '奶油苏打', '拉面', '白菜卷', '煎饺', '辣莲藕', '汉堡排',
    '儿童套餐', '鲷鱼烧', '炒饭', '奶油泡芙', '鲷鱼', '松茸', '桃子', '维也纳香肠', '草莓酱', '蕨菜',
    '可丽饼', '曲奇', '大阪烧', '豆腐', '啤酒', '烤鸡串', '草莓蛋糕', '炸虾卷', '肉丸', '综合沙拉',
  ],
  'numclo8.data': [
    '衣架', '信', '泳衣', '茶杯', '钥匙', '香烟', '学生书包', '高尔夫', '刀叉', '口红',
    '灭火器', '发带', '乒乓球', '锁', '游泳池', '光盘', '梳子', '筷子', '溜冰', '笔记本',
    '录像带', '足球', '雕刻刀', '浇花壶', '波浪', '海豚', '安全帽', '剪刀', '红绿灯', '卫生纸',
    '铲子', '桌子', '夹子', '刷子', '篮子', '投影仪', '卷轴', '拖鞋', '挎包', '高跟鞋',
    '摔跤擂台', '喷漆罐', '飞镖', '牙膏', '衣服', '单板滑雪', '降落伞', '独木舟', '橡皮图章', '开瓶器',
    '步行', '跑步', '俯卧撑', '仰卧起坐', '棒球', '网球', '跳绳', '举重', '跨栏', '接力',
    '跳远', '击剑', '单杠', '排球', '空手道', '卡拉OK', '瑜伽', '艺术体操', '自行车赛', '赛马',
    '滑雪', '冲浪', '游泳', '花样游泳', '橄榄球', '职业摔跤', '跳马', '羽毛球', '柔道', '拳击',
    '摩托艇赛', '舞蹈', '拔河', '跳高', '攀岩', '帆船运动', '跳水', '肥皂', '连指手套', '巫女服',
    '枕头', '床垫', '洗手液', '锅铲', '锅', '服务生制服', '汤勺', '海绵', '毛巾', '耳挖勺',
  ],
  'numclo9.data': [
    '加号', '减号', '除号', '围裙', '等号', '正方形', '圆形', '三角形', '正负号', '长方形',
    '百分号', '身高尺', '小于号', '数学符号∴', '数学符号∵', '圆周率π', '西格玛Σ', '西塔θ', '箭头', '欧米伽Ω',
    '夜景', '根号', '大于等于号', '小于等于号', '不等号', '数学符号·期间', '积分号', '希腊字母φ', '六边形', '等腰三角形',
    '乘号', '药袋', '大剪钳', '指甲钳', '温泉标志', '安全帽', '漱口', '广告飞艇', '心电图', '卫生间标志',
    '蛀牙', '大于号', '蚁丘', '好牙', '胃', '眼睛', '鼻子', '心脏', '嘴', '耳朵',
    'X光片', '蜂窝', '腿', '手臂', '骨头', '坏牙', '健康牙齿', '护腕', '袜子', '连衣裙',
    '牛仔裤', '运动裤', '背心', '围巾', '毛衣', '靴子', '穆勒鞋', '高帮运动鞋', '纽扣', '棺材',
    '马尾辫', '感冒', '皮鞋', '运动鞋', '手帕', '指甲', '针织帽', '烧杯', '脚链', '按摩',
    '粉饼盒', '睡衣', '背包', '耳环', '礼帽', '隐形眼镜', '脱毛器', '指甲锉', '指甲刀', '膏药',
    '受伤', '血压计', '裙子', '针织布', '香水', '领带', '贝雷帽', '膝盖受伤', '辫子', '饼图',
  ],
};
