// Bank 30 — 核心系统库 (Core Library Bank, CPU $C000-$DFFF)
// 基于 bank_30.asm 反汇编 + ROM 二进制分析
// Bank 30 是游戏的核心服务层，提供所有 Bank 31 及更高层模块调用的底层函数
const data = {
  bankId: 30,
  baseAddr: 0x3C000,   // PRG offset (Bank 0x1E * 0x2000)
  bankAddrBase: 0xC000, // CPU 映射窗口

  stats: {
    totalLines: 4835,
    codeBytes: 2100,
    dataBytes: 1700,
    unaccessedBytes: 1035,
    subroutineCount: 35,
    dataTableCount: 12,
    note: "Bank 30 是核心系统库，包含中断处理(RESET/NMI/IRQ)、跳转表(Jump Table)、球员数据处理、数学运算、Bank切换、场景管理等底层服务。通过 JMP 跳转表暴露统一 API 给 Bank 31 及上层调用。",
  },

  // ── 中断向量跳转表 ($C500-$C50F) ──
  // Bank 31 的 $FFFA-$FFFF 中断向量指向此处，每个入口 3 字节 (JMP $xxxx)
  interruptVectors: {
    NMI: { bankAddr: "$C500", target: "$C76E", desc: "NMI 中断 → JMP $C76E (NMI 主处理" },
    RESET: { bankAddr: "$C503", target: "$C64E", desc: "RESET/Boot → JMP $C64E (系统初始化)" },
    IRQ: { bankAddr: "$C506", target: "$C821", desc: "IRQ 中断 → JMP $C821 (IRQ 处理)" },
  },

  // ── 跳转表 (公共 API, $C509-$C5FF) ──
  // 通过 JMP 指令暴露给 Bank 31 及上层模块的统一入口
  // 每项 3 字节 (JMP $xxxx), 约 80+ 条目
  jumpTable: [
    { bankAddr: "$C509", target: "$CB99", desc: "音频/音效处理 ($CB99)" },
    { bankAddr: "$C50C", target: "$CD7C", desc: "球员数据指针加载 2" },
    { bankAddr: "$C50F", target: "$CAE7", desc: "内存复制 ($CAE7)" },
    { bankAddr: "$C512", target: "$CAF7", desc: "内存复制扩展 ($CAF7)" },
    { bankAddr: "$C515", target: "$CB0F", desc: "单球员处理 (核心函数)" },
    { bankAddr: "$C518", target: "$CB0D", desc: "球员处理备用" },
    { bankAddr: "$C51B", target: "$CB02", desc: "球员数据辅助" },
    { bankAddr: "$C51E", target: "$CD3C", desc: "16-bit 乘法/数学运算" },
    { bankAddr: "$C521", target: "$CD0D", desc: "数据辅助" },
    { bankAddr: "$C524", target: "$CBC2", desc: "内存操作" },
    { bankAddr: "$C527", target: "$CE08", desc: "Bank 切换 + 缓存写入" },
    { bankAddr: "$C52A", target: "$EF7F", desc: "两队初始化" },
    { bankAddr: "$C52D", target: "$CC46", desc: "某 ram 清零" },
    { bankAddr: "$C530", target: "$CC02", desc: "数据查询" },
    { bankAddr: "$C533", target: "$CCD2", desc: "数据变换" },
    { bankAddr: "$C536", target: "$CDC9", desc: "场地 Zone → XY 坐标解码" },
    { bankAddr: "$C539", target: "$CDE2", desc: "XY 坐标 → 场地 Zone 编码" },
    { bankAddr: "$C53C", target: "$F30F", desc: "Bank 1F 跳转" },
    { bankAddr: "$C53F", target: "$CE2D", desc: "Bank 切换 + JMP (长期跳转, 标记)" },
    { bankAddr: "$C542", target: "$CE4D", desc: "速度分量 Y 轴" },
    { bankAddr: "$C545", target: "$CE4A", desc: "速度分量 X 轴" },
    { bankAddr: "$C548", target: "$CE99", desc: "对手控球球员选择" },
    { bankAddr: "$C54B", target: "$CE6E", desc: "速度计算辅助" },
    { bankAddr: "$C54E", target: "$CBB0", desc: "PRG Bank 切換 (参数 A)" },
    { bankAddr: "$C551", target: "$CD77", desc: "球员数据指针加载 1" },
    { bankAddr: "$C554", target: "$CEFE", desc: "数据工具" },
    { bankAddr: "$C557", target: "$C6BE", desc: "PPU 操作" },
    { bankAddr: "$C55A", target: "$CF4F", desc: "控制器读取" },
    { bankAddr: "$C55D", target: "$CBF1", desc: "场景/特殊动作触发" },
    { bankAddr: "$C560", target: "$CF72", desc: "图形工具" },
    { bankAddr: "$C563", target: "$CF8F", desc: "图形工具 2" },
    { bankAddr: "$C566", target: "$F013", desc: "Bank 1F 处理" },
    { bankAddr: "$C569", target: "$CB35", desc: "球员速度处理" },
    { bankAddr: "$C56C", target: "$D022", desc: "随机数" },
    { bankAddr: "$C56F", target: "$D093", desc: "状态清理/初始化" },
    { bankAddr: "$C572", target: "$DB62", desc: "图形数据" },
    { bankAddr: "$C575", target: "$E233", desc: "Bank 31 比赛初始化" },
    { bankAddr: "$C578", target: "$D0D1", desc: "数学工具" },
    { bankAddr: "$C57B", target: "$C6BE", desc: "PPU 操作 (另一入口)" },
    // 更多跳转表条目...
  ],

  // ── 子程序函数列表 ──
  subroutines: [
    {
      startBankAddr: "$C64E",
      name: "RESET 系统初始化",
      length: "~190B",
      desc: "经典 NES 启动序列: SEI/CLD → LDX #$FF; TXS → 等待 VBlank → MMC3 mirroring 配置 → 清零 $0000-$07FF RAM → 设置 PPUCTRL/PPUMASK → 禁止 DMC → APU Frame Counter → Nametable 清零 → OAM 清零 → PPU 配置 → JMP $A200 (Bank 2) → $A21B 场景初始化",
      note: "完整追踪: RESET($FFF0)→$C503→$C64E→init→$CEFE→$C400: R6=Bank0, R7=Bank2 → $C41E JMP $A200 → Bank2 $8200 JMP $A21B (场景入口 A, 初始化场景并跳转)。Bank 2 是启动首个业务 Bank, 不是 Bank 1。Bank 1 是数据查询/选项屏幕服务, 通过 Bank 30 跳转表间接调用。详见 bank01_analysis.ts 和 bank02_analysis.ts",
    },
    {
      startBankAddr: "$C76E",
      name: "NMI 主处理",
      length: "~180B",
      desc: "NMI 每帧: 保存寄存器 → OAM DMA → PPU 滚动写入 → 命名表更新 → Bank 切换 → 读取控制器 → 声音处理 → 恢复寄存器 → RTI。VBlank 期间的核心入口",
    },
    {
      startBankAddr: "$C821",
      name: "IRQ 处理",
      length: "~40B",
      desc: "IRQ 每扫描线或 MMC3 计数器触发: 刷新 MMC3 IRQ 计数器 → 处理场次分割 → RTI",
    },
    {
      startBankAddr: "$CB0F",
      name: "单球员处理",
      length: "~130B",
      desc: "核心球员处理函数。A 值传入决定处理类型: 加载球员数据结构 → 坐标计算 → 特殊状态处理 → 动画更新。Bank 31 $E086/$E147/$E40F 等多处调用",
      note: "Bank 31 最高频调用函数之一",
    },
    {
      startBankAddr: "$CBB0",
      name: "PRG Bank 切換",
      length: "~18B",
      desc: "切换 MMC3 PRG Bank。参数 A 决定 bank 号和窗口。STA $8001/$A001 写入 MMC3 寄存器。Bank 31 中 $E050/$E235/$E38C 等调用",
    },
    {
      startBankAddr: "$CB8B",
      name: "清理/重置子程序",
      length: "~30B",
      desc: "初始化/清理工作区。A0 00; A9 F8 → 循环清零。Bank 31 $E38F/$E4BE 调用",
    },
    {
      startBankAddr: "$CBF1",
      name: "场景/特殊动作触发",
      length: "~25B",
      desc: "根据参数触发场景变换或特殊动作。LDX #$00; BC $0007 → 查表跳转。Bank 31 $EC02 调用",
    },
    {
      startBankAddr: "$CC46",
      name: "$0011/$0012 清零",
      length: "~15B",
      desc: "简单的归零操作: LDA #$00; STA ram_0011/0012。Bank 31 $E1CB/$ECB4 调用",
    },
    {
      startBankAddr: "$CD3C",
      name: "16-bit 乘法",
      length: "~60B",
      desc: "16-bit 数学运算: PHA; TXA → 乘法循环。Bank 31 $E826 调用",
    },
    {
      startBankAddr: "$CD77",
      name: "球员数据指针加载 1",
      length: "~5B",
      desc: "根据 $05FB 和 #$B0 XOR 来加载不同队的数据指针。Bank 31 $E27D/$E59D/$E85D 调用",
    },
    {
      startBankAddr: "$CD7C",
      name: "球员数据指针加载 2",
      length: "~14B",
      desc: "通过 A << 1 查表获取球员数据结构指针 (来自 $CD89 数据表)。Bank 31 $E060/$E0B1 等多处调用",
    },
    {
      startBankAddr: "$CDC9",
      name: "场地 Zone → XY 解码",
      length: "~25B",
      desc: "将场地区域编号($05FE)解码为 XY 坐标。检查 $C9 < $0C; 查表解码。Bank 31 $E7C3/$E7EF 调用",
    },
    {
      startBankAddr: "$CDE2",
      name: "XY → 场地 Zone 编码",
      length: "~38B",
      desc: "将球员 XY 坐标编码为场地区域。TXA SEC SBC #$30; 移位组合 → Zone 值。Bank 31 $E06D/$E5E6 等多处调用 (7 处引用)",
    },
    {
      startBankAddr: "$CE08",
      name: "Bank 切换 + 缓存保存",
      length: "~37B",
      desc: "保存当前 Bank 信息 → 切换 PRG Bank → 传递控制权。PHA; 保存状态 → 恢复。Bank 31 $E0CB/$E174 等多处调用 (5 处)",
    },
    {
      startBankAddr: "$CE2D",
      name: "Bank 切换 + JMP",
      length: "~23B",
      desc: "不保存状态直接切换 Bank 并跳转。设置 $22 位 6 → JMP 到新 Bank。Bank 31 中使用最频繁 (20+ 处引用)",
    },
    {
      startBankAddr: "$CE4A",
      name: "速度分量 X 计算",
      length: "~3B",
      desc: "计算 X 轴速度分量值。CLC ADC #$40 → 后续标记处理。Bank 31 $E760 调用",
    },
    {
      startBankAddr: "$CE4D",
      name: "速度分量 Y 计算",
      length: "~15B",
      desc: "计算 Y 轴速度分量值。ASL; PHP → 符号判断 → EOR 处理。Bank 31 $E76A 调用",
    },
    {
      startBankAddr: "$CE99",
      name: "对手控球球员选择",
      length: "~30B",
      desc: "根据当前队伍选择对手控球球员。STA $46; INC → 加载球员 ID。Bank 31 $E12A 调用",
    },
    {
      startBankAddr: "$D093",
      name: "状态清理/初始化",
      length: "~40B",
      desc: "LDA #$32; BIT $063E → 条件清理工作区 → 调用 $D0A9 初始化。Bank 31 $E680/$EBF3 调用",
    },
    {
      startBankAddr: "$D193",
      name: "球员数据初始化",
      length: "~30B",
      desc: "TAX; CLC ADC $05FF → 球员 ID 校验 → 球员数据块初始化。Bank 31 $E1EE 调用",
    },
    {
      startBankAddr: "$DE96",
      name: "场景跳转",
      length: "~30B",
      desc: "根据 $062B 游戏状态决定跳转到哪个场景 Bank (Bank 18/19 等)。LDA $062B; STA $30 → 查表 → CE2D 跳转。Bank 31 $E613/$E6CC 调用",
    },
    {
      startBankAddr: "$C4B2",
      name: "音频处理核心",
      length: "~50B",
      desc: "NMI 和主循环中调用的音频处理。读取 $00EE 计数器 → 调度 APU 帧计数器",
    },
    {
      startBankAddr: "$CAE7",
      name: "内存块复制",
      length: "~16B",
      desc: "从源地址复制数据到目标地址。支持可变长度复制",
    },
    {
      startBankAddr: "$CAF7",
      name: "内存复制扩展",
      length: "~11B",
      desc: "内存复制变体。不同寻址方式的数据复制",
    },
    {
      startBankAddr: "$D022",
      name: "随机数生成",
      length: "~15B",
      desc: "伪随机数生成器。用于 AI 决策、事件触发等",
    },
    {
      startBankAddr: "$CF4F",
      name: "控制器读取",
      length: "~35B",
      desc: "读取 Joypad 1/2 输入状态。存储到 RAM 控制变量",
    },
    {
      startBankAddr: "$EF7F",
      name: "两队初始化",
      length: "~80B",
      desc: "初始化比赛双方队伍数据。在 Bank 31 $E0DF 中通过 JMP $EF7F 调用",
    },
    {
      startBankAddr: "$C6A9",
      name: "PPU 背景清除",
      length: "~40B",
      desc: "清除 PPU NameTable 和 Attribute Table 到 $00。在 RESET 初始化期间调用",
    },
    {
      startBankAddr: "$C4B9",
      name: "音频帧更新",
      length: "~30B",
      desc: "每帧调用一次，处理 APU 音效参数更新",
    },
  ],

  // ── 数据表 ──
  dataTables: [
    {
      bankAddr: "$C000-$C4FF",
      displayName: "系统数据区 / Bank 开关表",
      length: "~1280B",
      desc: "Bank 30 的初始化参数表、音频参数、Bank 映射表、MMC3 配置数据。包含 ROM 标识数据",
      note: "开头 $AA $00 可能为 MMC3 识别码。后缀包含大量指针表用于场景/Bank 切换",
    },
    {
      bankAddr: "$C510-$C5FF",
      displayName: "公共 API 跳转表",
      length: "~240B (~80 entries × 3B)",
      desc: "通过 JMP 指令暴露所有 Bank 30 子程序的公共接口。Bank 31 不直接调用函数，先通过此跳转表间接调用",
      note: "每个 entry = [JMP $LO $HI] 三字节。覆盖 ~80 个公共 API 函数",
    },
    {
      bankAddr: "$CD89-$CDC8",
      displayName: "球员数据指针表",
      length: "~64B",
      desc: "球员数据结构指针表。$CD7C 中通过 A×2 索引，每个条目 2B 小端指向各球员数据块",
      note: "共 32 个球员(?)，涵盖两队的球员属性数据起始位置",
    },
    {
      bankAddr: "$D500-$D800",
      displayName: "速度/物理参数表",
      length: "~768B",
      desc: "含三角函数表、速度阈值表、物理模拟参数。供 $CE4A/$CE4D 速度计算和 $CDE2 Zone 编码使用",
    },
    {
      bankAddr: "$DAA0-$DB50",
      displayName: "场景跳转表",
      length: "~176B",
      desc: "游戏场景 ID → Bank 编号映射表。$DE96 查询此表决定场景切换目标",
      note: "Bank 18=动画, Bank 19=过场, Bank 17=菜单 等",
    },
    {
      bankAddr: "$DF00-$DF90",
      displayName: "控制器键位映射表",
      length: "~144B",
      desc: "按键扫描顺序/键值映射。$CF4F 控制器读取时使用",
    },
    {
      bankAddr: "$D600-$D700",
      displayName: "音频参数表",
      length: "~256B",
      desc: "APU 音效/音乐参数表 (频率、包络、持续时间)。$C4B2/$C4B9 音频处理函数消费",
    },
    {
      bankAddr: "$DE50-$DE95",
      displayName: "场景 ID 映射表",
      length: "~70B",
      desc: "游戏状态值 → 场景 ID 的映射关系。包括 $DE52=标题, $DE5E=菜单, $DE6C=比赛等分支",
    },
    {
      bankAddr: "$D850-$D8F6",
      displayName: "OAM DMA 缓冲区",
      length: "~166B",
      desc: "NMI 时执行的 OAM DMA 源数据缓冲区。Bank 31 写入精灵数据后 NMI 从此处 DMA 传输",
    },
  ],

  // ── RESET 流程详解 (ROM 直接追踪, 已验证) ──
  resetFlow: [
    { step: 1, addr: "Bank 31 $FFF0", desc: "RESET 向量: LDA #$00; STA $8000" },
    { step: 2, addr: "Bank 31 $FFF5", desc: "JMP $C503 (跳 Bank 30 RESET 入口)" },
    { step: 3, addr: "Bank 30 $C503", desc: "JMP $C64E (跳真正的初始化代码)" },
    { step: 4, addr: "Bank 30 $C64E", desc: "SEI (禁止中断) / CLD (清十进制模式) / LDX #$FF; TXS" },
    { step: 5, addr: "Bank 30 $C658", desc: "等待 PPU VBlank (轮询 $2002 bit7 两次)" },
    { step: 6, addr: "Bank 30 $C662", desc: "LDA #$C0; STA $A001 (MMC3 mirroring / PRG RAM protect)" },
    { step: 7, addr: "Bank 30 $C667", desc: "清零 $0000-$07FF (CPU RAM 初始化, 8 页循环)" },
    { step: 8, addr: "Bank 30 $C67A", desc: "$20=$08 (PPUCTRL 镜像); $21=$06; STA $2001 (PPUMASK)" },
    { step: 9, addr: "Bank 30 $C687", desc: "LDA #$00; STA $4010 (禁止 DMC); LDA #$40; STA $4017 (APU)" },
    { step: 10, addr: "Bank 30 $C6A5", desc: "JSR $CB35 (Nametable/PPU 清除, 含 VRAM 清零)" },
    { step: 11, addr: "Bank 30 $C6A8", desc: "JSR $CB8B (OAM 精灵缓冲区清零: LDA #$F8 填充 $0200-$02FF)" },
    { step: 12, addr: "Bank 30 $C6B5", desc: "STA $E000 (MMC3 bank 切换到 Bank 0); CLI (开中断)" },
    { step: 13, addr: "Bank 30 $C6BB", desc: "LDA #$00; JMP $CEFE → $CF1C: JMP $C400 (PPU 配置 + 参数设置)" },
    { step: 14, addr: "Bank 30 $C41E", desc: "JMP $A200 (Bank 2, 因 R7=Bank2 映射到 $A000-$BFFF)" },
    { step: 15, addr: "Bank 2 $A200→$A21B", desc: "→ 场景入口 A: LDX #$FF; TXS; 清零部分 RAM → JMP $9EED (场景业务初始化)" },
    { step: 16, addr: "Bank 2 $9EED+", desc: "✅ Bank 2 = 启动首屏/场景引擎 (RESET 后第一个执行业务的 Bank)。Bank 1 是独立的数据查询/选项屏幕服务, 不在启动链路中。" },
  ],

  // ── RAM 变量映射 ──
  ramMap: [
    { addr: "$0000-$001F", name: "Zero Page 工作区", desc: "指针/计数器/临时变量。$0020=PPUCTRL 镜像, $0021=PPUMASK 镜像" },
    { addr: "$0022", name: "Bank 切换状态", desc: "bit6=1 表示从非 Bank 30 跳入, CE2D 中使用" },
    { addr: "$0032-$0033", name: "BPM 相关数据", desc: "Bank 31 $E2BC BPM 更新中修改的高频数据指针" },
    { addr: "$0034", name: "当前球员指针", desc: "当前处理的球员对象指针 (base)" },
    { addr: "$003C-$003D", name: "动画帧指针", desc: "Bank 31 精灵动画数据指针" },
    { addr: "$0043", name: "距离阈值", desc: "Bank 31 近距球员筛选的曼哈顿距离阈值" },
    { addr: "$0046", name: "对手球员ID", desc: "$CE99 中设置的对手控球球员编号" },
    { addr: "$00E2", name: "随机数/角度", desc: "Bank 31 方向计算中的随机角度值" },
    { addr: "$00EE", name: "音频帧计数器", desc: "$C4B2 音频处理中的帧计数" },
    { addr: "$043B-$043D", name: "进球动画状态", desc: "$043B=类型 $043C=状态 $043D=参数" },
    { addr: "$0469", name: "场地偏移", desc: "Bank 31 $E233 初始化的场地坐标偏移" },
    { addr: "$0490-$0491", name: "暂停恢复数据", desc: "Bank 31 $EC08 暂停恢复的音频参数镜像" },
    { addr: "$04A5-$04E4", name: "OAM 缓冲 (mirror)", desc: "Bank 31 动画排版写入的目标缓冲区, NMI 读取并 DMA" },
    { addr: "$0515", name: "动画锁", desc: "$01=动画播放中 $80=完成" },
    { addr: "$0516", name: "控制器状态", desc: "bit7=暂停 bit4=启动 bit1=方向" },
    { addr: "$0410-$0430", name: "PPU 缓冲", desc: "NMI 写入 PPU 的缓冲数据区" },
    { addr: "$05FB", name: "控制队伍", desc: "$00=Team1 $0B=Team2" },
    { addr: "$05FC", name: "交换比分", desc: "半场切换交换" },
    { addr: "$05FD", name: "当前控球球员", desc: "当前控球球员编号" },
    { addr: "$05FE", name: "当前场地区域", desc: "当前 Zone 值" },
    { addr: "$05FF", name: "球员迭代标记", desc: "触发 $E074 球员迭代" },
    { addr: "$0600", name: "近距球员计数", desc: "AI 筛选产生的候选人数" },
    { addr: "$0601-$060A", name: "近距球员缓冲区", desc: "最多 10 名筛选出的球员" },
    { addr: "$0613", name: "回合计数器", desc: "≥5 触发半场切换检查" },
    { addr: "$0614", name: "动作时钟", desc: "每帧递减倒计时" },
    { addr: "$0618", name: "BPM 计数器", desc: "每帧自增,上限 11" },
    { addr: "$062A", name: "场地区域标志", desc: "bit7=已改变" },
    { addr: "$062B", name: "游戏状态", desc: "$04=射门/进球" },
    { addr: "$062D", name: "暂停/越界", desc: "非0触发清场" },
    { addr: "$0634-$0637", name: "球/球员坐标", desc: "16-bit X/Y 固定点" },
    { addr: "$0638", name: "目标场地区域", desc: "球寻路目标" },
  ],

  // ── Bank 31 → Bank 30 交叉引用 ──
  crossRefs: [
    { addr: "$CB0F", name: "单球员处理", locations: "$E086, $E147, $E40F, $E775, $E842, $EB88" },
    { addr: "$CBB0", name: "PRG Bank 切换", locations: "$E050, $E235, $E38C, $E4C3, $E57C, $E5B7" },
    { addr: "$CB8B", name: "清理/重置", locations: "$E38F, $E4BE" },
    { addr: "$CBF1", name: "场景触发", locations: "$EC02" },
    { addr: "$CC46", name: "清零 $11/$12", locations: "$E1CB, $ECB4" },
    { addr: "$CD3C", name: "16-bit 乘法", locations: "$E826" },
    { addr: "$CD77", name: "球员指针 1", locations: "$E27D, $E59D, $E85D" },
    { addr: "$CD7C", name: "球员指针 2", locations: "$E060, $E0B1, $E133, $E1D6, $E31C, $E450, $E4EE" },
    { addr: "$CDC9", name: "Zone→XY 解码", locations: "$E7C3, $E7EF" },
    { addr: "$CDE2", name: "XY→Zone 编码", locations: "$E06D, $E5E6, $E6BE, $E702, $E7A0, $E7DA, $E86E" },
    { addr: "$CE08", name: "Bank 切换+缓存", locations: "$E0CB, $E174, $E1DB, $E47B, $E2D3" },
    { addr: "$CE2D", name: "Bank 跳转", locations: "$E047, $E0A7, $E1AB, $E1C4, $E1DE, $E243, $E2B3, $E39A, $E4CE, $E587, $E5C5, $E5D9, $E641, $E65E, $E670, $E8AC, $E8BE, $E8D0, $EC25, $EC6D" },
    { addr: "$CE4A", name: "速度分量 X", locations: "$E760" },
    { addr: "$CE4D", name: "速度分量 Y", locations: "$E76A" },
    { addr: "$CE99", name: "对手球员选择", locations: "$E12A" },
    { addr: "$D093", name: "状态清理", locations: "$E680, $EBF3" },
    { addr: "$D193", name: "球员初始化", locations: "$E1EE" },
    { addr: "$DE96", name: "场景跳转", locations: "$E613, $E6CC" },
    { addr: "$EF7F", name: "两队初始化", locations: "$E0DF (via JMP)" },
    // Bank 1 交叉引用
    { addr: "$C50C", name: "球员数据指针", locations: "Bank1 $A3B8, $A615, $AEE2, $AF39 (通过 JSR)" },
    { addr: "$C527", name: "Bank 切换+缓存", locations: "Bank1 $ABC9, $AC10 (通过 JSR)" },
    { addr: "$C53C", name: "Bank 跳转", locations: "Bank1 $A5CB, $AC8F, $AF09 (通过 JSR)" },
    { addr: "$C54B", name: "速度计算", locations: "Bank1 $ACE1 (通过 JSR)" },
    { addr: "$C66A", name: "初始化辅助", locations: "Bank1 $BF16 (通过 JSR)" },
  ],

  // ── 关键架构说明 ──
  architecture: {
    role: "核心系统库 / 服务层 (Core Library / Service Layer) — Bank 31 的唯一对外接口",
    pattern: "Bank 30 使用 JMP 跳转表模式暴露公共 API。Bank 31 及上层不直接调用 Bank 30 内部函数，而是通过跳转表入口间接调用 (如 JMP $CBB0 实际跳转到真正的 Bank 切换代码)。这样即使 Bank 30 内部重组，API 接口保持稳定。\n\nBank 31 为什么不能直接调 Bank 00? 因为 Bank 31 固定在 $E000-$FFFF, $8000-$9FFF 是可切换窗口，Bank 31 无从知道该窗口当前映射的是 Bank 00 还是 Bank 26、24 等。但 Bank 30 固定在 $C000，永远可见。所以 Bank 31 所有外部调用统一经 Bank 30 跳转表，Bank 30 内部再负责 MMC3 切 bank → 调用目标。路径: 31 → 30(JMP表) → 30内部切换MMC3 → 00/01/02/...",
    bootFlow: "CPU RESET → Bank31 $FFF0 (复位MMC3) → Bank30 $C503→$C64E (硬件初始化) → RAM/PPU/OAM 清零 → $CEFE→$C400: R6=Bank0(→$8000常驻服务层), R7=Bank2(→$A000场景控制器) → JMP $A200 → Bank02 $A21B 场景初始化（密集调用 Bank00 服务：$9A43/$98A0/$9B7F/$9F69） → JMP $9EED (Bank 00 主循环，最终目的地，永不退出)",
    nniFlow: "VBlank → Bank 30 $C500 (跳转表) → $C76E (NMI处理) → OAM DMA → PPU 更新 → 控制器读取 → RTI",
    irqFlow: "MMC3 计数器 → Bank 30 $C506 (跳转表) → $C821 → 刷新计数器 → RTI",
    dependees: ["Bank 0 (系统服务层+主循环引擎: $C400 通过 R6=0 映射到 $8000，Bank 02 场景初始化密集调用其 $9A43/$98A0/$9B7F/$9F69，$9EED 是最终主循环)", "Bank 2 (场景控制器: RESET后首个业务Bank，$A21B初始化后 JMP $9EED 进入 Bank00 主循环，通过 R7=2 映射到 $A000)", "Bank 1 (数据查询/选项屏幕服务: 通过跳转表间接调用)", "Bank 31 (比赛主循环 + 中断: 所有外部调用全部走 Bank 30 跳转表)", "Bank 18/19 (场景)", "Bank 17 (菜单)", "所有非固定 Bank 通过 NMI 间接依赖"],
  },
};

export default data;
