/**
 * Copy full PPU (src/ppu/index.ts) → mini-audio/emu/ppu-stub.ts
 * Fixing imports and class name for audio-only emulator compatibility.
 */
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, 'src/ppu/index.ts');
const DEST = path.join(__dirname, 'mini-audio/emu/ppu-stub.ts');

let code = fs.readFileSync(SRC, 'utf8');

// Fix import paths (now relative to mini-audio/emu/)
code = code.replace(
  'import Tile from "../tile";',
  'import Tile from "./tile";'
);
code = code.replace(
  'import { fromJSON, toJSON } from "../utils";',
  'import { fromJSON, toJSON } from "./utils";'
);
// NameTable, PaletteTable imports stay "./" — same relative meaning.

// Rename class for compatibility with nes-audio.ts
code = code.replace(
  'class PPU {',
  'export class PPUStub {'
);
code = code.replace(
  'export default PPU;',
  'export default PPUStub;'
);

// Strip ui.writeFrame calls (no UI in audio mode)
code = code.replace(
  'this.nes.ui.writeFrame(buffer);',
  '// [audio-mode] ui.writeFrame skipped'
);

// PPUStub doesn't expose bindCPU; _bindCPU lets nes-audio set it directly per constructor.
code = code.replace(
  /this\.nes\.cpu/g,
  'this.nes.cpu'
);

const header = [
  '/**',
  ' * PPU — 完整实现，源自 src/ppu/index.ts。',
  ' * 音频驱动也使用完整 PPU 以确保游戏逻辑不受 stub 影响。',
  ' * 类名保持 PPUStub 兼容 nes-audio.ts。',
  ' * AUTO-GENERATED by _copy_ppu.cjs — do not edit directly.',
  ' */',
  '',
].join('\n');

fs.writeFileSync(DEST, header + '\n' + code, 'utf8');
console.log('OK: wrote', code.length + header.length, 'bytes to', DEST);
