declare class CPU {
    IRQ_NORMAL: number;
    IRQ_NMI: number;
    IRQ_RESET: number;
    static JSON_PROPERTIES: string[];
    nes: any;
    mem: Uint8Array;
    REG_ACC: number;
    REG_X: number;
    REG_Y: number;
    REG_SP: number;
    REG_PC: number;
    REG_PC_NEW: number;
    REG_STATUS: number;
    F_CARRY: number;
    F_DECIMAL: number;
    F_INTERRUPT: number;
    F_INTERRUPT_NEW: number;
    F_OVERFLOW: number;
    F_SIGN: number;
    F_ZERO: number;
    F_NOTUSED: number;
    F_NOTUSED_NEW: number;
    F_BRK: number;
    F_BRK_NEW: number;
    cyclesToHalt: number;
    crash: boolean;
    irqRequested: boolean;
    irqType: number | null;
    nmiRaised: boolean;
    nmiPending: boolean;
    nmiImmediate: boolean;
    dataBus: number;
    instrBusCycles: number;
    apuCatchupCycles: number;
    _cpuCycleBase: number;
    nmiRaisedAtCycle: number;
    nmiDotsRemainingInStep: number;
    _dmcFetchCycles: number;
    /** trace callback: (pc, opcode, cycles, frameCount) */
    _traceCb: ((pc: number, opcode: number, cycles: number, frame: number) => void) | null;
    _instrPC: number;
    /** Enable debug logging for PC entering non-ROM areas */
    debugNonROM: boolean;
    constructor(nes: any);
    emulate(): number;
    loadFromCartridge(addr: number): number;
    _loadFromCartridgePlain(addr: number): number;
    _loadFromCartridgeWithGameGenie(addr: number): number;
    _updateCartridgeLoader(): void;
    load(addr: number): number;
    loadDirect(addr: number): number;
    load16bit(addr: number): number;
    write(addr: number, val: number): void;
    requestIrq(type: number): void;
    push(value: number): void;
    pull(): number;
    _cyclesToNextDmcFetch(): number;
    _takeBranch(opaddr: number, addr: number): number;
    pageCrossed(addr1: number, addr2: number): boolean;
    haltCycles(cycles: number): void;
    doNonMaskableInterrupt(status: number): void;
    doResetInterrupt(): void;
    doIrq(status: number): void;
    getStatus(): number;
    setStatus(st: number): void;
    setStatusFromStack(st: number): void;
    toJSON(): any;
    fromJSON(s: any): void;
}
export default CPU;
