import Mapper0 from "./mapper0";
interface PulseState {
    enabled: boolean;
    dutyCycle: number;
    lengthHalt: boolean;
    constantVolume: boolean;
    volume: number;
    timer: number;
    timerCounter: number;
    lengthCounter: number;
    envelopeCounter: number;
    envelopeDecay: number;
    envelopeStart: boolean;
    sequencePos: number;
}
declare class Mapper5 extends Mapper0 {
    static mapperName: string;
    prgMode: number;
    prgBankReg: Uint8Array;
    prgRam: Uint8Array;
    prgRamProtectA: number;
    prgRamProtectB: number;
    chrMode: number;
    chrBankA: Uint16Array;
    chrBankB: Uint16Array;
    chrUpperBits: number;
    lastChrWrite: number;
    ntMapping: Uint8Array;
    exramMode: number;
    exram: Uint8Array;
    fillTile: number;
    fillAttr: number;
    irqTarget: number;
    irqEnabled: boolean;
    irqPending: boolean;
    inFrame: boolean;
    irqCounter: number;
    multA: number;
    multB: number;
    splitEnabled: boolean;
    splitRight: boolean;
    splitTile: number;
    splitScroll: number;
    splitPage: number;
    pulse1: PulseState;
    pulse2: PulseState;
    pcmValue: number;
    pcmReadMode: boolean;
    pcmIrqEnabled: boolean;
    audioEnabled: number;
    _chrBankTarget: number;
    constructor(nes: any);
    _initPulse(): PulseState;
    load(address: number): number;
    _readPrg(address: number): number;
    _readPrgRom32k(bank32k: number, offset: number): number;
    _readPrgRom16k(bank16k: number, offset: number): number;
    _readPrgRom8k(bank8k: number, offset: number): number;
    write(address: number, value: number): void;
    _writePrg(address: number, value: number): void;
    _isPrgRamWritable(): boolean;
    _syncPrg(): void;
    _syncChr(): void;
    _applyChrSetA(): void;
    _applyChrSetB(): void;
    _syncNametables(): void;
    _populateNameTable(ntIndex: number, vramBase: number): void;
    _syncExramToVram(exAddr: number): void;
    _writePulse(pulse: PulseState, reg: number, value: number): void;
    clockIrqCounter(): void;
    _clockPulseLengthCounter(pulse: PulseState): void;
    onBgRender(): void;
    onSpriteRender(): void;
    getSpritePatternTile(index: number): any;
    getBgTileData(baseTile: any, tileIndex: number, ht: number, vt: number): any;
    loadROM(): void;
    toJSON(): any;
    fromJSON(s: any): void;
}
export default Mapper5;
